# Curation entries, session 82 (2023). Written by reading every NELIS
# Overview digest. Merged into curation-map.json by curation-assemble.py.
E = {}

def add(key, topic, theme, rel):
    E[key] = {"plain_topic": topic, "theme": theme, "relevance": rel}

# --- chunk 1 (AB3-AB247) ---
add("82:AB3", "Cut Permanent School Fund financial reports from quarterly to annual", "spending-oversight", "adjacent")
add("82:AB4", "Would have let the Commission on School Funding meet year-round and adjusted the teacher-standards commission", "school-funding", "core")
add("82:AB25", "CPR liability protection including school staff; liability law, not education policy", "context", "context")
add("82:AB33", "Expanded allowed investments of the Permanent School Fund; state finance", "context", "context")
add("82:AB36", "Veterans council membership; not K-12", "context", "context")
add("82:AB37", "Behavioral health workforce center at colleges; postsecondary", "context", "context")
add("82:AB42", "Would have extended class-size ratio rules to charters and required public reporting on ratio variances", "classroom-time-content", "core")
add("82:AB43", "Adjusted deadlines for school emergency operations plans", "facilities-operations", "adjacent")
add("82:AB52", "Open Meeting Law changes; not K-12", "context", "context")
add("82:AB54", "Education-department cleanup: attendance, accountability reports, hospital-school reimbursements", "accountability-governance", "core")
add("82:AB65", "Barred school board votes after 11 p.m. and revised discrimination-report investigations", "accountability-governance", "core")
add("82:AB69", "Extended health-provider loan repayment to behavioral health; not K-12", "context", "context")
add("82:AB72", "Created an advisory committee on the safety and well-being of school staff", "teacher-workforce", "core")
add("82:AB73", "Let pupils wear tribal regalia and religious or cultural objects at graduation", "student-supports", "adjacent")
add("82:AB81", "Concealed-carry in vehicles on school property; firearms law, not education policy", "context", "context")
add("82:AB93", "Automated speed cameras in school zones; traffic enforcement", "context", "context")
add("82:AB113", "Would have created the Office of Early Childhood Systems in the Governor's Office, with money attached", "early-learning-reading", "core")
add("82:AB114", "Broadened the Early Childhood Advisory Council to include health, tribal, and parent members", "early-learning-reading", "core")
add("82:AB115", "Overdose prevention programs; not K-12", "context", "context")
add("82:AB128", "Money for the outdoor education grant program", "classroom-time-content", "adjacent")
add("82:AB131", "Urban forestry program; not K-12", "context", "context")
add("82:AB132", "Clark County opioid task force; not K-12", "context", "context")
add("82:AB135", "Birth certificates and IDs for homeless people, touching pupil ID cards; not education policy", "context", "context")
add("82:AB147", "Teledentistry rules; not K-12", "context", "context")
add("82:AB149", "Would have created an independent Inspector General of Education to audit anyone receiving education money", "spending-oversight", "core")
add("82:AB164", "Outdoor recreation grant program administration; recreation policy with pupil-program edge", "classroom-time-content", "adjacent")
add("82:AB172", "Would have made districts share employee contact lists with unions semiannually", "teacher-workforce", "adjacent")
add("82:AB175", "Added four appointed nonvoting members to the Clark County school board", "accountability-governance", "core")
add("82:AB182", "Would have required a bachelor's degree for teaching licenses and created a substitute-teacher license", "teacher-workforce", "core")
add("82:AB185", "Gave military children charter enrollment preference and transfer accommodations", "student-supports", "adjacent")
add("82:AB187", "Would have banned three-cueing reading instruction in kindergarten through grade 2", "early-learning-reading", "core")
add("82:AB194", "Would have expanded suspension and expulsion authority for assaults on staff or pupils", "student-supports", "core")
add("82:AB199", "Chiropractor head-injury clearances; health licensing", "context", "context")
add("82:AB201", "Would have added oversight of the children's behavioral health system; vetoed; health policy with school ties", "student-supports", "adjacent")
add("82:AB207", "Let schools buy liability insurance for pupils in work-based learning", "classroom-time-content", "adjacent")
add("82:AB217", "College fee waivers for formerly homeless pupils; postsecondary", "context", "context")
add("82:AB222", "Would have gave school employees a full year of pension credit at 900 hours", "teacher-workforce", "adjacent")
add("82:AB228", "Would have raised required high school social studies from three to four credits including geography", "classroom-time-content", "core")
add("82:AB236", "Psychologist title protections; not K-12", "context", "context")
add("82:AB237", "Medicaid appropriations; not K-12", "context", "context")
add("82:AB238", "Would have required training for school and child-welfare staff to identify sexually exploited children", "student-supports", "adjacent")
add("82:AB239", "State employee merit awards plus family-engagement council tweaks; administration", "context", "context")
add("82:AB241", "Made the college-and-career-ready course load the default high school enrollment", "testing-graduation", "core")
add("82:AB243", "Legislative interim committee mechanics, touching a teacher task force deadline; process", "context", "context")
add("82:AB245", "Required school agreements with power-based violence victim organizations and referrals", "student-supports", "adjacent")
add("82:AB247", "Would have created Nevada-written college and career readiness exams required for a diploma", "testing-graduation", "core")

# --- chunk 2 (AB255-AB515) ---
add("82:AB255", "Adoption assistance until high school graduation; child welfare", "context", "context")
add("82:AB256", "Streamlined work-based learning approvals and volunteer supervision rules", "classroom-time-content", "core")
add("82:AB258", "Nonprofit donor confidentiality; not K-12", "context", "context")
add("82:AB264", "Protected perfect-attendance awards and credit for religious-holiday absences", "student-supports", "adjacent")
add("82:AB265", "Would have created a statewide children's mental health consortium; vetoed; health governance with school ties", "student-supports", "adjacent")
add("82:AB269", "Would have let consistently effective teachers skip to fewer evaluations", "accountability-governance", "core")
add("82:AB273", "Money for Elko County to replace a school building", "facilities-operations", "adjacent")
add("82:AB274", "Required financial-literacy credits inside high school social studies and restructured the advisory council", "classroom-time-content", "core")
add("82:AB280", "Would have made districts dedicate per-pupil money to behavior schools for removed pupils", "school-funding", "core")
add("82:AB282", "Would have required a $450 monthly health-insurance subsidy for full-time substitute teachers", "teacher-workforce", "core")
add("82:AB285", "Replaced the restorative-discipline mandate with progressive discipline plans", "student-supports", "core")
add("82:AB296", "Would have required reporting of class time spent on testing, with corrective plans past 2 percent", "testing-graduation", "core")
add("82:AB301", "Police officer benefit definitions including school police; employment benefits", "context", "context")
add("82:AB308", "Would have required orientations for J-1 visa teachers and ethical international recruiting", "teacher-workforce", "core")
add("82:AB317", "Would have allowed dual credit from accredited out-of-state institutions", "testing-graduation", "adjacent")
add("82:AB319", "Would have funded universal free school breakfast and lunch", "student-supports", "core")
add("82:AB323", "Would have required a statewide teacher-recruitment strategic plan and reshaped the standards commission", "teacher-workforce", "core")
add("82:AB330", "Extended discipline rules to charters, set appeal timelines, and required education during expulsions", "student-supports", "core")
add("82:AB335", "Would have cut the grade-3 class-size cap to 16 and paid teachers extra in oversized classes", "classroom-time-content", "core")
add("82:AB339", "Would have required accountability reporting on achievement of chronically absent and substitute-taught pupils", "testing-graduation", "core")
add("82:AB341", "Would have changed which unions nominate teacher members of state education boards", "accountability-governance", "adjacent")
add("82:AB344", "Would have repealed the cost adjustment factor in the Pupil-Centered Funding Plan", "school-funding", "core")
add("82:AB347", "Money for dual-credit program grants", "testing-graduation", "adjacent")
add("82:AB348", "Piloted virtual early-childhood family engagement before kindergarten, with money attached", "early-learning-reading", "core")
add("82:AB352", "Would have added weighted funding for low-achieving pupils who are not English learners", "school-funding", "core")
add("82:AB353", "Would have created an Inspector General under the Controller to audit school districts", "spending-oversight", "core")
add("82:AB357", "Would have replaced the HIV/reproduction course with evidence-based sexuality education", "classroom-time-content", "core")
add("82:AB360", "Would have given teachers sole authority over the grades they assign", "testing-graduation", "core")
add("82:AB372", "Let the university system partner on early-childhood family tools", "early-learning-reading", "adjacent")
add("82:AB385", "Would have expanded private-school scholarship eligibility and tax credits", "charters-choice", "core")
add("82:AB395", "Would have created the Financial Oversight of School Spending Committee to review district budgets quarterly", "spending-oversight", "core")
add("82:AB399", "Created a legislative Subcommittee on Education Accountability over spending and outcomes", "spending-oversight", "core")
add("82:AB400", "Education omnibus: early-literacy account, school-funding commission duties, charter transportation money", "early-learning-reading", "core")
add("82:AB409", "Juneteenth commission; cultural affairs, not K-12", "context", "context")
add("82:AB420", "Would have carved a rural regional school district out of Clark County, with $6 million", "accountability-governance", "core")
add("82:AB421", "Consumer data tax; not K-12", "context", "context")
add("82:AB423", "Would have barred school boards from restricting pupil access by identity and from late-night votes", "accountability-governance", "core")
add("82:AB428", "Created teacher-pipeline career pathways and a Nevada Grown Educator tuition account", "teacher-workforce", "core")
add("82:AB445", "Would have given tax abatements to businesses providing children's mental health services", "student-supports", "adjacent")
add("82:AB458", "Would have allowed temporary advances from the Education Stabilization Account to the State Education Fund", "school-funding", "core")
add("82:AB459", "Would have required the education budget to at least keep pace with revenue growth or inflation plus enrollment", "school-funding", "core")
add("82:AB463", "Moved child-care licensing between divisions and adjusted the early childhood council", "early-learning-reading", "adjacent")
add("82:AB490", "Academic medical district; not K-12", "context", "context")
add("82:AB497", "Would have let pupils transfer to any school with open seats outside their zone", "charters-choice", "core")
add("82:AB503", "Tightened background-check rules for school volunteers and license applicants", "facilities-operations", "adjacent")
add("82:AB515", "Created the Incentivizing Pathways to Teaching grant program with tuition help and stipends", "teacher-workforce", "core")

# --- chunk 3 (AB517-SB220); bills pending enrichment handled in a later pass ---
add("82:AB517", "Required recurring legislative performance audits of the two biggest districts and the charter authority", "spending-oversight", "core")
add("82:AB519", "Required an Elko County property tax for school buildings and eased rural capital grants", "facilities-operations", "adjacent")
add("82:AB522", "State employee pay act; not K-12", "context", "context")
add("82:AB523", "Adjusted State Education Fund revenues, advances, and the inflation factor for per-pupil funding", "school-funding", "core")
add("82:SB10", "Let the state infrastructure bank finance rural K-12 school facilities", "facilities-operations", "adjacent")
add("82:SB29", "Tax refund interest; not K-12", "context", "context")
add("82:SB38", "Made it a felony for school staff to groom or solicit pupils", "facilities-operations", "adjacent")
add("82:SB100", "Money for White Pine County to build an elementary school", "facilities-operations", "adjacent")
add("82:SB112", "Groundwater assessments; not K-12", "context", "context")
add("82:SB114", "Loosened sports-transfer eligibility; interscholastic athletics", "context", "context")
add("82:SB121", "Age of consent; criminal law, not K-12", "context", "context")
add("82:SB124", "Rerouted mining tax proceeds through the State Education Fund and stabilization account", "school-funding", "adjacent")
add("82:SB144", "Would have created tax-credit donations for career and technical education programs", "classroom-time-content", "core")
add("82:SB148", "Would have recentralized custodial and support staffing decisions from Clark County school precincts", "accountability-governance", "core")
add("82:SB149", "Would have required elementary math improvement plans, math specialists, and early math-reading checks", "testing-graduation", "core")
add("82:SB151", "Would have kept federal support labels out of star ratings, revised diplomas and evaluations, added mentorship", "testing-graduation", "core")
add("82:SB152", "Would have made restorative-justice plans optional before removing or suspending pupils", "student-supports", "core")
add("82:SB158", "Would have let parents request cameras in self-contained special-education classrooms", "student-supports", "core")
add("82:SB165", "Emerging technology task force; not K-12", "context", "context")
add("82:SB171", "Firearms after hate-crime convictions; not K-12", "context", "context")
add("82:SB188", "Concealed carry on campuses; firearms law", "context", "context")
add("82:SB189", "Money for Communities In Schools to provide integrated student supports", "student-supports", "core")
add("82:SB196", "Restricted coaches from forcing out-of-season club participation; athletics", "context", "context")
add("82:SB197", "Fentanyl penalties; not K-12", "context", "context")
add("82:SB199", "Would have required district programs for alternative educational opportunities outside school", "classroom-time-content", "core")
add("82:SB200", "Would have revived education savings accounts for private schooling", "charters-choice", "core")
add("82:SB206", "Would have required shared instructional models and converted the lowest-rated schools to Department charters", "accountability-governance", "core")
add("82:SB210", "Board appointment diversity; not K-12", "context", "context")
add("82:SB212", "Would have recreated the Teachers' School Supplies Assistance Account for classroom supplies", "teacher-workforce", "core")
add("82:SB214", "Abolished the STEM council and educational technology commission, moving duties to the education department", "classroom-time-content", "core")
add("82:SB220", "Would have expanded Opportunity Scholarship eligibility, minimum grants, and tax credits", "charters-choice", "core")

# --- chunk 4 (SB228-SB503) ---
add("82:SB228", "PERS investment restrictions; not K-12", "context", "context")
add("82:SB231", "Money for districts budgeting raises for teachers and support staff (the 2023 educator pay match)", "teacher-workforce", "core")
add("82:SB236", "Money for civics education programs in schools", "classroom-time-content", "core")
add("82:SB244", "Money for school-garden programs in public schools", "student-supports", "adjacent")
add("82:SB251", "Would have made transfer and reassignment of non-teaching district staff a mandatory bargaining subject", "teacher-workforce", "adjacent")
add("82:SB256", "Would have funded charter school facilities per pupil through a new account", "charters-choice", "core")
add("82:SB277", "Cannabis regulation; not K-12", "context", "context")
add("82:SB282", "Tightened Clark County precinct rules: bargaining-compliant hiring and carryforward money for pupils", "accountability-governance", "core")
add("82:SB285", "Money for civics education programs for pupils and adults", "classroom-time-content", "core")
add("82:SB291", "Let student teachers substitute sooner and funded the teaching institute", "teacher-workforce", "core")
add("82:SB292", "Made principals at-will when their school's rating falls and half the teachers seek transfers", "accountability-governance", "core")
add("82:SB294", "Gun locking devices with school notice provisions; firearms law", "context", "context")
add("82:SB295", "Would have gave every principal their school's full budget and required posting learning materials online", "spending-oversight", "core")
add("82:SB308", "Would have cut PERS vesting from 10 to 5 years and limited J-1 teacher recruiter fees", "teacher-workforce", "adjacent")
add("82:SB313", "Would have aligned health-class standards with social-emotional learning and required educator mental-health training", "student-supports", "core")
add("82:SB315", "Rights for pupils with disabilities in transition services", "student-supports", "adjacent")
add("82:SB317", "Homeless mailing addresses incl. school enrollment; welfare policy", "context", "context")
add("82:SB329", "Would have ordered an interim study of school district budgeting and required reports", "spending-oversight", "core")
add("82:SB337", "Criminal forfeiture; not K-12", "context", "context")
add("82:SB339", "Money for grants supplying classrooms for teachers and support staff", "teacher-workforce", "core")
add("82:SB340", "Would have required district summer school plans with transportation and meals for 2023-24", "classroom-time-content", "core")
add("82:SB343", "Fentanyl trafficking; not K-12", "context", "context")
add("82:SB344", "Would have protected public comment at school board meetings, required audits, and set substitute licensing rules", "accountability-governance", "core")
add("82:SB345", "Postsecondary institution licensing; not K-12", "context", "context")
add("82:SB347", "Higher-education funding commission; postsecondary", "context", "context")
add("82:SB357", "Would have created transportation modernization grants so pupils can reach schools of choice", "charters-choice", "core")
add("82:SB359", "Juvenile community service; not K-12", "context", "context")
add("82:SB366", "Would have created an expert committee for child personal-safety curriculum standards", "classroom-time-content", "adjacent")
add("82:SB383", "Would have let Clark County cities form municipal school districts", "accountability-governance", "core")
add("82:SB394", "Would have capped economic-development tax abatements at $500,000", "context", "context")
add("82:SB396", "Digital products tax; not K-12", "context", "context")
add("82:SB404", "Election procedures; not K-12", "context", "context")
add("82:SB419", "Health information exchange; not K-12", "context", "context")
add("82:SB425", "Created the Commission on Innovation and Excellence in Education to benchmark and plan, with money", "accountability-governance", "core")
add("82:SB428", "Diaper sales-tax ballot question; Local School Support Tax touched mechanically", "context", "context")
add("82:SB429", "Paid leave conditions on tax abatements; not K-12", "context", "context")
add("82:SB438", "Teacher recruitment, preparation, and retention measures", "teacher-workforce", "core")
add("82:SB442", "Enacted the Interstate Teacher Mobility Compact easing licenses for teachers moving to Nevada", "teacher-workforce", "core")
add("82:SB503", "The biennium K-12 funding act for 2023-2025", "school-funding", "core")

# --- chunk 5 + previously-pending bills (SB9-SB508, SCR2) ---
add("82:SB9", "Education cleanup: later expenditure-report deadlines, more CTE leadership money, ended end-of-course finals", "testing-graduation", "core")
add("82:SB46", "Would have replaced empowerment schools with a Program of Empowerment Districts", "accountability-governance", "core")
add("82:SB47", "Would have let districts build or rent housing for teachers and capped license fees", "teacher-workforce", "core")
add("82:SB48", "Air pollution penalty proceeds redirected away from school district funds; environment policy", "context", "context")
add("82:SB50", "National Guard sales-tax holiday; not K-12", "context", "context")
add("82:SB56", "Would have created a Commission on School Modernization to streamline education statutes", "accountability-governance", "core")
add("82:SB64", "Would have added appointed members to county school boards and required district audits", "accountability-governance", "core")
add("82:SB65", "Would have required school board candidates to certify governance training before running", "accountability-governance", "core")
add("82:SB71", "Broadened the teacher retention task force to education support professionals, with money", "teacher-workforce", "core")
add("82:SB72", "Ordered six interim studies: pupil mental health, teacher workload, licensing, graduation trends and more", "accountability-governance", "core")
add("82:SB79", "Would have banned charging fees for access to public school property or employees", "facilities-operations", "adjacent")
add("82:SB80", "Required head-injury policies covering classroom effects, not just sports return", "student-supports", "adjacent")
add("82:SB84", "Would have let teachers keep home addresses confidential in public records", "teacher-workforce", "adjacent")
add("82:SB86", "Criminal justice provisions; not K-12", "context", "context")
add("82:SB98", "Required grade-level performance metrics, eased stabilization transfers, and funded school-funding studies", "school-funding", "core")
add("82:SB431", "Governor's office staffing; not K-12", "context", "context")
add("82:SB434", "Made substitute teachers eligible for public pensions", "teacher-workforce", "adjacent")
add("82:SB439", "Communicable disease services; not K-12", "context", "context")
add("82:SB474", "Money for the outdoor education grant program", "classroom-time-content", "adjacent")
add("82:SB477", "Tourism department administration; not K-12", "context", "context")
add("82:SB484", "Election audit appropriations; not K-12", "context", "context")
add("82:SB500", "Money to replace the education department's computer hardware", "spending-oversight", "adjacent")
add("82:SB508", "Money for the private-school Opportunity Scholarship program", "charters-choice", "core")
add("82:SCR2", "Declared April 2023 Financial Literacy Month; resolution", "classroom-time-content", "adjacent")
