# Curation entries, session 81 (2021). Written by reading every NELIS
# Overview digest. Merged into curation-map.json by curation-assemble.py.
E = {}

def add(key, topic, theme, rel):
    E[key] = {"plain_topic": topic, "theme": theme, "relevance": rel}

# --- chunk 1 (AB19-AB348) ---
add("81:AB19", "Redefined social studies to include civics, financial literacy, and multicultural education", "classroom-time-content", "core")
add("81:AB38", "Streamlined career-and-technical education advisory committees and work-based learning rules", "classroom-time-content", "core")
add("81:AB54", "Traffic safety committee; not K-12", "context", "context")
add("81:AB56", "Would have had a State Board subcommittee study Holocaust and genocide instruction", "classroom-time-content", "core")
add("81:AB57", "Zeroed out pupil growth in educator evaluations for 2021-22, restoring 15 percent the next year", "accountability-governance", "core")
add("81:AB67", "Rewrote suspension and expulsion rules, defining terms and protecting pupils with disabilities", "student-supports", "core")
add("81:AB68", "Adjusted charter application timelines, performance frameworks, and school closures", "charters-choice", "core")
add("81:AB82", "Would have required instruction on founding principles of American government with reports", "classroom-time-content", "core")
add("81:AB88", "Banned racially discriminatory school names, mascots, and imagery without tribal permission", "accountability-governance", "adjacent")
add("81:AB90", "Interim study of intercounty development projects; not K-12", "context", "context")
add("81:AB105", "Would have added parents and pupils to Nevada Interscholastic Activities Association boards", "context", "context")
add("81:AB108", "Would have created a statewide independent Office of the Inspector General", "spending-oversight", "adjacent")
add("81:AB109", "Raised the share of charter school teachers who must be licensed from 70 to 80 percent", "charters-choice", "core")
add("81:AB116", "Civil penalties for traffic infractions; not K-12", "context", "context")
add("81:AB122", "Would have funded grants for virtual prekindergarten programs", "early-learning-reading", "core")
add("81:AB159", "COVID liability protection for public schools; legal immunity, not education policy", "facilities-operations", "adjacent")
add("81:AB167", "Put mental health crisis lines on pupil identification cards", "student-supports", "core")
add("81:AB184", "Small business advocacy office; not K-12", "context", "context")
add("81:AB194", "Added restorative-justice reporting and appeal rights to school discipline", "student-supports", "core")
add("81:AB195", "Required districts to track English learners, protect their program rights, and post information", "student-supports", "core")
add("81:AB204", "Moved the Office of Workforce Innovation; workforce administration, not K-12", "context", "context")
add("81:AB205", "Let schools stock opioid-overdose antidotes under a health professional's order", "student-supports", "adjacent")
add("81:AB206", "Counted military-family distance-education pupils for school funding before relocation", "school-funding", "adjacent")
add("81:AB208", "Let unions and trade groups help teach career and technical courses and set CTE endorsement experience", "classroom-time-content", "core")
add("81:AB215", "Opened adult high school diploma courses to 17-year-olds with four years of high school", "testing-graduation", "adjacent")
add("81:AB224", "Required free menstrual products in secondary school bathrooms with accountability reporting", "student-supports", "adjacent")
add("81:AB225", "Required alternative competency demonstrations in teacher licensing exams for people with disabilities", "teacher-workforce", "core")
add("81:AB231", "Required a State Board subcommittee on Holocaust and genocide instruction", "classroom-time-content", "core")
add("81:AB235", "Made high schools help seniors complete the federal student aid application", "testing-graduation", "adjacent")
add("81:AB255", "Would have made three of seven Clark County school board seats appointed", "accountability-governance", "core")
add("81:AB257", "Required schools to assess and improve ventilation and air filtration where money allows", "facilities-operations", "adjacent")
add("81:AB261", "Required instruction on the history and contributions of diverse groups and inclusive textbooks", "classroom-time-content", "core")
add("81:AB265", "Created an alternative route to licensure for school administrators", "teacher-workforce", "core")
add("81:AB266", "Tightened who counts in class-size ratios and required posting teacher vacancy numbers", "classroom-time-content", "core")
add("81:AB273", "Created a statewide children's mental health consortium", "student-supports", "adjacent")
add("81:AB280", "Inclusive single-stall restrooms; not K-12 policy", "context", "context")
add("81:AB288", "Raised the income limit for private-school Opportunity Scholarships to 400 percent of poverty", "charters-choice", "core")
add("81:AB296", "Civil action for doxing; not K-12", "context", "context")
add("81:AB305", "Raised the school-district fund balance shielded from collective bargaining", "teacher-workforce", "adjacent")
add("81:AB306", "Penalized false reports to the SafeVoice school-safety tip line", "student-supports", "adjacent")
add("81:AB319", "Dual-credit pilot at the College of Southern Nevada for high school pupils", "testing-graduation", "adjacent")
add("81:AB322", "Cannabis event licensing; not K-12", "context", "context")
add("81:AB329", "Opened full-time distance education across district lines and unlimited distance-charter enrollment", "charters-choice", "core")
add("81:AB330", "Credit for vocational training toward occupational licenses; not K-12", "context", "context")
add("81:AB345", "Drug-checking products; not K-12", "context", "context")
add("81:AB348", "Patient Protection Commission; not K-12", "context", "context")

# --- chunk 2 (AB352-SB151) ---
add("81:AB352", "Would have declared a legal right to a high-quality public education for every pupil", "accountability-governance", "core")
add("81:AB353", "Required biennial sexual-misconduct climate surveys and stronger grievance processes in schools", "student-supports", "adjacent")
add("81:AB355", "Appropriations for various health and education purposes", "school-funding", "adjacent")
add("81:AB364", "Would have made school board members teach one supervised classroom day each year", "accountability-governance", "core")
add("81:AB366", "Mental-health training recordings; health records, not K-12", "context", "context")
add("81:AB367", "Eased the combined American government-economics course and required disciplinary-skills instruction", "classroom-time-content", "core")
add("81:AB371", "Extended the school bullying framework to cover discrimination based on race", "student-supports", "core")
add("81:AB372", "Doctor loan-repayment program; health workforce, not K-12", "context", "context")
add("81:AB374", "Substance use working group; not K-12", "context", "context")
add("81:AB376", "Immigration model policies including for schools; immigration policy, not education outcomes", "context", "context")
add("81:AB415", "Ordered an interim study of the statewide school accountability and rating system", "accountability-governance", "core")
add("81:AB417", "Tightened school-bus inspection follow-up and reporting", "facilities-operations", "adjacent")
add("81:AB418", "Required exit surveys for teachers leaving districts, analyzed for retention lessons", "teacher-workforce", "core")
add("81:AB419", "Set governance standards, training, and disclosure rules for charter school boards and low-rated charters", "charters-choice", "core")
add("81:AB420", "Redefined for-profit educational management organizations serving charter schools", "charters-choice", "core")
add("81:AB447", "Money for the We the People civics program in schools", "classroom-time-content", "core")
add("81:AB450", "Community-college workforce study; postsecondary, not K-12", "context", "context")
add("81:AB459", "Moved the Office of Workforce Innovation; administration, not K-12", "context", "context")
add("81:AB485", "Emergency management reorganization; not K-12", "context", "context")
add("81:AB494", "The state general appropriations act for 2021-2023", "school-funding", "adjacent")
add("81:AB495", "New gold and silver mining excise tax with proceeds routed to the State Education Fund", "school-funding", "adjacent")
add("81:AJR8", "Would have asked voters to repeal the ban on public funds for sectarian purposes, easing private-school aid", "charters-choice", "core")
add("81:AJR13", "Election certification by the Legislature; not K-12", "context", "context")
add("81:SB2", "Moved kindergarten reading checks to early-learning assessments and trimmed some pupil measurements", "early-learning-reading", "core")
add("81:SB27", "Let the state superintendent investigate school personnel and delegate license suspensions", "accountability-governance", "core")
add("81:SB36", "Turned school crisis committees into all-hazards emergency planning committees", "facilities-operations", "adjacent")
add("81:SB39", "Digital token payments; not K-12", "context", "context")
add("81:SB40", "All-payer health claims database; not K-12", "context", "context")
add("81:SB66", "Made the state track pupils' home Internet and device access and work to close gaps", "classroom-time-content", "core")
add("81:SB68", "State investments touching the Permanent School Fund; finance, not education policy", "context", "context")
add("81:SB69", "Peer recovery specialist certification; not K-12", "context", "context")
add("81:SB76", "Education-agency cleanup: fewer reports, renamed teacher council, abolished technology and literacy councils", "accountability-governance", "core")
add("81:SB83", "Let Nevada pause school ratings and exams when federal accountability rules are waived", "testing-graduation", "core")
add("81:SB91", "Would have let juniors choose between a college or a career readiness assessment for graduation", "testing-graduation", "core")
add("81:SB92", "Added robotics to approved career and technical education subjects", "classroom-time-content", "core")
add("81:SB102", "Would have moved the kindergarten age cutoff to the first day of school", "early-learning-reading", "core")
add("81:SB111", "Would have made some Clark and Washoe school board seats appointed instead of elected", "accountability-governance", "core")
add("81:SB116", "Mental-health first-aid training plus reporting on distance education's mental-health effects on pupils and teachers", "student-supports", "adjacent")
add("81:SB118", "College support program for low-income first-generation students; postsecondary", "context", "context")
add("81:SB120", "Would have made principals at-will employees when their school's rating falls and teachers flee", "accountability-governance", "core")
add("81:SB126", "Required school libraries with teacher librarians in the two urban counties", "classroom-time-content", "core")
add("81:SB131", "State grants office reorganization; not K-12", "context", "context")
add("81:SB132", "Money for juvenile assessment center support services to Clark County pupils", "student-supports", "adjacent")
add("81:SB135", "Banned charging fees for access to public school property or employees", "facilities-operations", "adjacent")
add("81:SB142", "Repealed the shield keeping school ending fund balances out of collective bargaining", "teacher-workforce", "adjacent")
add("81:SB151", "Required the urban districts to plan and report on improving counselor and support-staff ratios", "student-supports", "core")

# --- chunk 3 (SB152-SB402) ---
add("81:SB152", "Would have required big schools to post their learning materials online for parents", "classroom-time-content", "core")
add("81:SB157", "Loosened rules on which pupils private-school scholarship organizations may fund", "charters-choice", "core")
add("81:SB160", "Widened who can offer dual-credit courses, including out-of-state colleges", "testing-graduation", "adjacent")
add("81:SB166", "Hate crime penalties; not K-12", "context", "context")
add("81:SB169", "Recast special-education categories around developmental trauma and behavioral dysregulation", "student-supports", "core")
add("81:SB172", "Would have standardized grading weight for dual-credit and IB courses", "testing-graduation", "core")
add("81:SB173", "Authorized COVID learning-loss plans with expanded summer school, transportation, and meals", "classroom-time-content", "core")
add("81:SB182", "Would have required PE to include activity scientifically shown to reduce obesity", "classroom-time-content", "core")
add("81:SB188", "Matched-savings accounts for low-income families; not K-12", "context", "context")
add("81:SB194", "Created the State Seal of Civics and required civics in social studies instruction", "classroom-time-content", "core")
add("81:SB195", "Made colleges grant credit for high school State Seal subjects", "testing-graduation", "adjacent")
add("81:SB199", "Barred race discrimination in schools and employment, including hair and cultural traits", "student-supports", "adjacent")
add("81:SB202", "Counted computer-coding credits as world-language credits", "classroom-time-content", "core")
add("81:SB210", "Required education plans for children admitted to psychiatric residential treatment", "student-supports", "adjacent")
add("81:SB215", "Loosened alternative schedules and let distance-education pupils finish courses early", "classroom-time-content", "core")
add("81:SB217", "Behavior analyst licensing transfer; health boards, not K-12", "context", "context")
add("81:SB220", "Would have made every district run alternative educational opportunity programs with apprenticeships", "classroom-time-content", "core")
add("81:SB224", "Protected collective-bargaining transfer rules when Clark County precincts pick their staff", "teacher-workforce", "adjacent")
add("81:SB226", "Steered career-technical education toward high-need industries with grants and reporting", "classroom-time-content", "core")
add("81:SB230", "Required trauma training for all school employees and reporting on integrated student supports in distance education", "student-supports", "core")
add("81:SB243", "Let teachers keep home addresses confidential in public records", "teacher-workforce", "adjacent")
add("81:SB244", "Banned GPA conditions for specialty-school and charter enrollment and standardized course grade weights", "testing-graduation", "core")
add("81:SB249", "Excused school absences for behavioral health and put crisis lines on pupil ID cards", "student-supports", "core")
add("81:SB250", "Counted adult diploma-course pupils for school funding", "school-funding", "adjacent")
add("81:SB255", "Supplier diversity office; not K-12", "context", "context")
add("81:SB265", "Focused work-based learning on high-demand industries with priority for underserved pupils", "classroom-time-content", "core")
add("81:SB272", "Would have created the Nevada Educator Corps tutoring force, with money attached", "classroom-time-content", "core")
add("81:SB273", "Would have funded a literacy grant account for elementary reading programs", "early-learning-reading", "core")
add("81:SB306", "Would have revived education savings accounts under an Office of Educational Choice", "charters-choice", "core")
add("81:SB312", "Steered $8 million of federal relief to enroll at least 500 pre-K pupils", "early-learning-reading", "core")
add("81:SB316", "Steered $25 million of federal relief to a pilot for pupils who missed graduation in the pandemic", "testing-graduation", "core")
add("81:SB321", "Would have split community colleges from the university system; postsecondary governance", "context", "context")
add("81:SB327", "Race discrimination protections in employment and education; civil rights, partial school angle", "student-supports", "adjacent")
add("81:SB330", "Would have required plain-language expenditure reports and per-pupil budgeting from every district", "spending-oversight", "core")
add("81:SB333", "Would have created tax-credit donations for charter school facilities", "charters-choice", "core")
add("81:SB343", "Would have funded leased classroom space to reduce class sizes, paid by cannabis taxes", "classroom-time-content", "core")
add("81:SB352", "Accelerated student teaching for working paraprofessionals and recognized out-of-state experience", "teacher-workforce", "core")
add("81:SB353", "Would have capped time spent on tests and required review of redundant assessments", "testing-graduation", "core")
add("81:SB354", "Extended restorative-justice requirements to suspensions and recognized schools reducing discipline removals", "student-supports", "core")
add("81:SB355", "Civil infractions procedure; not K-12", "context", "context")
add("81:SB363", "Required charter schools to disclose payments to management companies", "charters-choice", "core")
add("81:SB374", "Digital products tax; not K-12", "context", "context")
add("81:SB375", "Would have created an Enhanced Classroom Funding Account on top of the funding formula", "school-funding", "core")
add("81:SB391", "Teledentistry and dental staffing; not K-12", "context", "context")
add("81:SB395", "Would have required voter-approved property taxes for small-county school building projects", "facilities-operations", "adjacent")
add("81:SB402", "Required education licenses within 30 days and reciprocal licensing agreements", "teacher-workforce", "core")

# --- chunk 4 (SB439-SB463) ---
add("81:SB439", "Overhauled State Education Fund revenues and the mechanics of the Pupil-Centered Funding Plan", "school-funding", "core")
add("81:SB441", "Sales tax seller permits; Local School Support Tax touched mechanically", "context", "context")
add("81:SB444", "Supplemental money to the school account after pandemic revenue drops", "school-funding", "core")
add("81:SB450", "Let districts stretch existing voter-approved bonding for school buildings", "facilities-operations", "adjacent")
add("81:SB458", "The biennium K-12 funding act: per-pupil base and weighted funding under the new plan", "school-funding", "core")
add("81:SB460", "General appropriations to state agencies, education among them", "school-funding", "adjacent")
add("81:SB463", "Money transferred to certain charter schools", "charters-choice", "adjacent")
