# Curation entries, session 83 (2025). Written by reading every NELIS
# Overview digest. Merged into curation-map.json by curation-assemble.py.
E = {}

def add(key, topic, theme, rel):
    E[key] = {"plain_topic": topic, "theme": theme, "relevance": rel}

# --- chunk 1 (AB24-AB327); short-title bills revisited in a later pass ---
add("83:AB24", "Turned the competency-based education pilot into a permanent approval process", "testing-graduation", "core")
add("83:AB33", "Would have created an Inspector General under the Controller to audit anyone receiving public money", "spending-oversight", "adjacent")
add("83:AB34", "Sentencing rules; not K-12", "context", "context")
add("83:AB39", "Adjusted charter authority membership and charter renewal requirements", "charters-choice", "core")
add("83:AB138", "Required curriculum standards on sexual-abuse awareness and prevention", "classroom-time-content", "core")
add("83:AB139", "Money for dual-credit program grants", "testing-graduation", "adjacent")
add("83:AB153", "FAFSA help for incarcerated people; corrections, not K-12", "context", "context")
add("83:AB154", "Would have created an independent statewide Office of the Inspector General", "spending-oversight", "adjacent")
add("83:AB155", "Made class-size and support-staff ratios mandatory subjects of collective bargaining", "classroom-time-content", "core")
add("83:AB156", "Would have given Clark County's appointed trustees full rights, set term limits, and curbed workshop votes", "accountability-governance", "core")
add("83:AB165", "Created the Outdoor Education Council with school designations", "classroom-time-content", "adjacent")
add("83:AB177", "Speech-language pathology licensing; health boards", "context", "context")
add("83:AB184", "Interscholastic athletics governance and transfers; sports rules", "context", "context")
add("83:AB195", "Would have empowered appointed Clark County trustees and set term limits", "accountability-governance", "core")
add("83:AB203", "Cannabis packaging; not K-12", "context", "context")
add("83:AB205", "Switched sex-education consent from opt-in to opt-out forms", "classroom-time-content", "core")
add("83:AB210", "Allowed state exams to be taken remotely by distance-education pupils", "testing-graduation", "core")
add("83:AB212", "Extended and renamed the virtual early-childhood family engagement program, with money", "early-learning-reading", "core")
add("83:AB214", "Would have expanded Opportunity Scholarship eligibility, priorities, and tax credits", "charters-choice", "core")
add("83:AB215", "Child labor hour limits; employment law", "context", "context")
add("83:AB217", "Barred schools from aiding immigration enforcement without a court order", "student-supports", "adjacent")
add("83:AB224", "Would have issued $100 million in bonds for emergency school-building repairs", "facilities-operations", "adjacent")
add("83:AB232", "Full pension credit for school employees at 900 hours across eight months", "teacher-workforce", "adjacent")
add("83:AB236", "Changed which unions nominate teachers to state education boards", "accountability-governance", "adjacent")
add("83:AB238", "Film studio tax credits; economic development", "context", "context")
add("83:AB240", "Would have required school sports teams to be designated by biological sex", "context", "context")
add("83:AB247", "Made American Sign Language a world-language course and improved meeting access", "classroom-time-content", "adjacent")
add("83:AB257", "Money for the Nevada School of the Arts programs", "classroom-time-content", "adjacent")
add("83:AB268", "Would have funded universal free school breakfast and lunch", "student-supports", "core")
add("83:AB272", "Forensic exam payments; not K-12", "context", "context")
add("83:AB286", "Allowed alternative assessments of teaching competency for licensure", "teacher-workforce", "core")
add("83:AB288", "Money for White Pine County to build an elementary school", "facilities-operations", "adjacent")
add("83:AB289", "College financial literacy course; postsecondary", "context", "context")
add("83:AB292", "Required new elementary buildings to include designated pre-K space", "early-learning-reading", "core")
add("83:AB298", "Made full-time school counselors mandatory instead of money-permitting", "student-supports", "core")
add("83:AB307", "Would have raised the retail cannabis tax with proceeds tied to the State Education Fund", "school-funding", "adjacent")
add("83:AB314", "Health-care career pathways and tuition reimbursement; workforce policy", "context", "context")
add("83:AB316", "Added a nonvoting pupil trustee to every county school board", "accountability-governance", "core")
add("83:AB323", "Required community notice and limits before school closures; eased adding pre-K", "accountability-governance", "core")
add("83:AB327", "Ordered legislative audits of Vegas PBS and education-department broadcasting grants", "spending-oversight", "adjacent")

# --- chunk 1 stragglers, enriched late ---
add("83:AB47", "Would have sent excess Education Stabilization money to districts for teacher retention, recruitment, and training", "school-funding", "core")
add("83:AB48", "Added screening steps for discrimination and bullying reports with perpetrator transfers", "student-supports", "core")
add("83:AB49", "Let out-of-state licensed teachers start work provisionally for up to a year", "teacher-workforce", "core")
add("83:AB53", "Required at least 20 minutes of daily outdoor recess in elementary school and banned withholding it for academics or behavior", "classroom-time-content", "core")
add("83:AB77", "Economic-development tax abatement criteria; not K-12", "context", "context")
add("83:AB93", "Police-officer benefit definitions including school police; employment benefits", "context", "context")

# --- chunk 2 (AB335-AB432); remainder curated after enrichment completes ---
add("83:AB335", "Required district English-learner administrators, teacher training, and achievement-gap goals in school plans", "student-supports", "core")
add("83:AB345", "Required a college-outcomes data dashboard tracking remediation of high school graduates", "testing-graduation", "adjacent")
add("83:AB355", "Kept school-repair funds from reverting and eased rural capital grants", "facilities-operations", "adjacent")
add("83:AB359", "Bullion sales-tax ballot question; Local School Support Tax touched mechanically", "context", "context")
add("83:AB364", "Would have adjusted Opportunity Scholarship rules and tax credits", "charters-choice", "core")
add("83:AB374", "Would have required monthly mental-health workshops for every grade", "student-supports", "core")
add("83:AB383", "Set state criteria for vendors of high-impact tutoring programs", "classroom-time-content", "core")
add("83:AB386", "Let Washoe County pilot an alternative elementary literacy assessment", "early-learning-reading", "core")
add("83:AB389", "Streamlined pupil-performance metrics and had the innovation commission review achievement and financial accountability reports", "accountability-governance", "core")
add("83:AB391", "Required accountability reporting on achievement of chronically absent and substitute-taught pupils", "testing-graduation", "core")
add("83:AB398", "Funded extra pay for hard-to-fill teaching positions and curbed weighted-funding diversions", "teacher-workforce", "core")
add("83:AB401", "Ended the college and career readiness assessment as a diploma requirement", "testing-graduation", "core")
add("83:AB406", "Banned artificial intelligence from doing counselors' mental-health work in schools", "student-supports", "core")
add("83:AB412", "Funded school-mapping data grants for law enforcement and camera rules", "facilities-operations", "adjacent")
add("83:AB416", "Restricted school and public libraries from limiting access to library materials", "classroom-time-content", "adjacent")
add("83:AB420", "Required annual public reports on use of force by school police", "facilities-operations", "adjacent")
add("83:AB425", "Gave teachers sole authority over the grades they assign", "testing-graduation", "core")
add("83:AB426", "Tightened Clark County precinct budgeting votes and organizational team rules", "accountability-governance", "core")
add("83:AB427", "State private-equity investments touching the Permanent School Fund; finance", "context", "context")
add("83:AB432", "State security operations center; not K-12", "context", "context")
add("83:AB435", "Would have created a charter school facility fund with bonds and an optional district property tax", "charters-choice", "core")
add("83:AB445", "Shielded school and public library staff from liability for providing access to materials", "classroom-time-content", "adjacent")
add("83:AB453", "Digital products tax; not K-12", "context", "context")
add("83:AB454", "Required school heart-emergency response plans and CPR-certified coaches (Smart Heart Law)", "student-supports", "adjacent")
add("83:AB460", "Guardianship nomination forms; not K-12", "context", "context")
add("83:AB462", "Industrial park authorities with a school career-coordination clause; economic development", "context", "context")
add("83:AB464", "Would have locked in course standards on genocide and ethnic histories against repeal", "classroom-time-content", "core")
add("83:AB465", "Gave schools civil immunity for harassment incidents if they enforce required policies", "facilities-operations", "adjacent")
add("83:AB468", "Extended hospital-school reimbursements to certain private placements", "school-funding", "adjacent")
add("83:AB472", "Limited recruiter fees districts can pay for J-1 and H-1B visa teachers", "teacher-workforce", "core")
add("83:AB491", "Election administration; not K-12", "context", "context")
add("83:AB494", "Required contingency plans if federal education laws (IDEA, FERPA, ESSA) are repealed", "accountability-governance", "core")
add("83:AB495", "Required charter closure or restart after three straight years of low ratings, with a pause until 2027", "charters-choice", "core")
add("83:AB501", "Allowed academic credit for approved outdoor recreational activities", "classroom-time-content", "adjacent")
add("83:AB506", "Eliminated reports incl. the Legislative Bureau of Educational Accountability; administration", "accountability-governance", "adjacent")
add("83:AB508", "Required Economic Forum estimates for the State Education Fund and revised cannabis-tax routing", "school-funding", "core")
add("83:AB516", "Made Medicaid reimbursement work for health services delivered at schools", "student-supports", "core")
add("83:AB527", "Allowed stop-arm cameras on school buses; traffic enforcement", "facilities-operations", "adjacent")
add("83:AB531", "Required a real-time pupil attendance dashboard and a task force on comparative metrics", "accountability-governance", "core")
add("83:AB533", "Opened cross-zone school transfers with grant-funded transportation", "charters-choice", "core")
add("83:AB535", "Sales-tax exemption administration; not K-12", "context", "context")
add("83:AB538", "Tax-credit board procedures; not K-12", "context", "context")
add("83:AB539", "Authorized career coaches in middle and junior high schools", "classroom-time-content", "core")
add("83:AB546", "Registration fee exemption for charter school vehicles; administrative", "charters-choice", "adjacent")
add("83:AB547", "State hiring rules; not K-12", "context", "context")
add("83:AB548", "Vessel fees; not K-12", "context", "context")

# --- chunk 3 (AB571-SB229) ---
add("83:AB571", "Money to the education department for surveys, federal-grant offsets, technology, and studies", "school-funding", "adjacent")
add("83:AB573", "Money to run the Incentivizing Pathways to Teaching grant program", "teacher-workforce", "core")
add("83:AB579", "Money to replace the educator-licensure computer system", "teacher-workforce", "adjacent")
add("83:AB584", "Created a district-level accountability system with interventions for low-performing districts and streamlined reporting", "accountability-governance", "core")
add("83:AB592", "State employee salary act; not K-12", "context", "context")
add("83:AB599", "Tightened Opportunity Scholarship registration, reporting, and carryforward rules", "charters-choice", "core")
add("83:AJR9", "Resolution urging Congress to keep immigration enforcement out of schools", "student-supports", "adjacent")
add("83:SB15", "Local government administration; not K-12", "context", "context")
add("83:SB21", "Adjusted the outdoor education grant program's advisory board", "classroom-time-content", "adjacent")
add("83:SB38", "Let emergency managers share school emergency plans with public-safety agencies", "facilities-operations", "adjacent")
add("83:SB45", "Refocused career and technical education grants on advanced courses and eased reporting", "classroom-time-content", "core")
add("83:SB48", "Regional planning timelines; not K-12", "context", "context")
add("83:SB52", "Refined English-learner counting, long-term learner definitions, and Read by Grade 3 exemptions", "student-supports", "core")
add("83:SB57", "Body camera rules including school police; law enforcement administration", "context", "context")
add("83:SB58", "Widened who counts for state pre-K grants and tied grant size to per-pupil funding", "early-learning-reading", "core")
add("83:SB59", "Banned grooming by school staff and created license holds for accused educators", "teacher-workforce", "core")
add("83:SB71", "Government purchasing; not K-12", "context", "context")
add("83:SB74", "Election procedures; not K-12", "context", "context")
add("83:SB78", "Boards and commissions consolidation; not K-12", "context", "context")
add("83:SB81", "Required school-climate and exit surveys of school employees, with hospital-school reimbursement changes", "teacher-workforce", "core")
add("83:SB82", "Would have created an Office of Early Childhood Services in the Governor's Office", "early-learning-reading", "core")
add("83:SB89", "Firearms after hate crimes; not K-12", "context", "context")
add("83:SB90", "Money for grants supplying classrooms for teachers and support staff", "teacher-workforce", "core")
add("83:SB98", "Renamed world languages 'languages other than English' and studied endorsement rules", "classroom-time-content", "adjacent")
add("83:SB104", "Money for school gardens and other nonprofits", "student-supports", "adjacent")
add("83:SB112", "Would have required school sports teams designated by biological sex", "context", "context")
add("83:SB115", "Allowed stipends for bilingual-education teachers", "teacher-workforce", "core")
add("83:SB131", "Required human-trafficking prevention instruction standards for grades 6-12", "classroom-time-content", "core")
add("83:SB135", "Money for Communities In Schools integrated student supports", "student-supports", "core")
add("83:SB161", "Added binding arbitration paths for teacher bargaining and limited unpaid extra work", "teacher-workforce", "core")
add("83:SB172", "Agricultural workers' rights; not K-12", "context", "context")
add("83:SB174", "Required policies letting pupils with disabilities receive private medical services at school", "student-supports", "core")
add("83:SB175", "Let certified military JROTC instructors earn teaching endorsements", "teacher-workforce", "adjacent")
add("83:SB176", "Piloted paying certified nursing assistant exam costs for CTE pupils, with money", "classroom-time-content", "core")
add("83:SB177", "Protected homeless and foster pupils in discipline with meetings and alternative placements", "student-supports", "core")
add("83:SB178", "Contingent money for a Las Vegas community facility; not school policy", "context", "context")
add("83:SB181", "University license plates; not K-12", "context", "context")
add("83:SB192", "Health care requirements; not K-12", "context", "context")
add("83:SB196", "Heavy equipment fees; not K-12", "context", "context")
add("83:SB199", "Artificial intelligence regulation; not K-12", "context", "context")
add("83:SB216", "Money to United Citizens Foundation for K-12-related services", "student-supports", "adjacent")
add("83:SB220", "Film tax credits with an education-diversification label; economic development", "context", "context")
add("83:SB224", "Required shared instructional models and conversion of the lowest-rated schools to Department charters", "accountability-governance", "core")
add("83:SB226", "Interim committee mechanics touching a teacher task force; process", "context", "context")
add("83:SB227", "Enacted the School Psychologist Interstate Licensure Compact", "teacher-workforce", "core")
add("83:SB229", "Extended financial-literacy instruction to the earliest grades and refined the state seal", "classroom-time-content", "core")

# --- chunk 4 (SB245-SCR5) ---
add("83:SB245", "Created the Advisory Council on Civics Education and funded civics awards", "classroom-time-content", "core")
add("83:SB248", "Would have required every school to post a public catalog of library and instructional materials", "classroom-time-content", "core")
add("83:SB252", "Would have created education savings accounts funded by tax-credit donations", "charters-choice", "core")
add("83:SB253", "Would have funded charter facilities per pupil and posted top-10 school rankings", "charters-choice", "core")
add("83:SB254", "Required a model policy for screening pupils' behavioral, social, and emotional well-being", "student-supports", "core")
add("83:SB255", "Would have required school-climate and exit surveys of school staff", "teacher-workforce", "core")
add("83:SB259", "Narrowed a county sales tax away from early childhood and teacher-incentive uses", "school-funding", "adjacent")
add("83:SB272", "Sports transfer eligibility appeals; athletics", "context", "context")
add("83:SB277", "Required school social workers where money allows and eased their licensure pipeline", "student-supports", "core")
add("83:SB278", "Improved licensure access and dropped local assessments from Read by Grade 3 deficiency decisions", "early-learning-reading", "core")
add("83:SB314", "Aligned health standards with social-emotional learning and required teacher mental-health training", "student-supports", "core")
add("83:SB318", "Required charter schools to document public-works compliance for construction over $100,000", "charters-choice", "adjacent")
add("83:SB328", "Required accountability reporting on broken school air conditioning and school-level salary budgets", "facilities-operations", "adjacent")
add("83:SB331", "Set complaint procedures for discrimination reports and strengthened family-engagement policy", "student-supports", "core")
add("83:SB343", "4-H and cooperative extension; not K-12", "context", "context")
add("83:SB351", "Would have double-weighted growth of the lowest-scoring pupils in school ratings", "testing-graduation", "core")
add("83:SB357", "Required Braille and assistive-technology standards for visually impaired pupils", "student-supports", "core")
add("83:SB368", "Kept federal special-education law in force in Nevada if Congress repeals it", "student-supports", "core")
add("83:SB374", "Required staff training on discipline and a system to flag disproportionate discipline", "student-supports", "core")
add("83:SB383", "Juvenile community service; not K-12", "context", "context")
add("83:SB385", "Would have tied tax abatements to workforce development plans; economic development", "context", "context")
add("83:SB392", "Digital products tax; not K-12", "context", "context")
add("83:SB396", "Required literacy-instruction training and capped special-education class loads", "student-supports", "core")
add("83:SB400", "Guaranteed comparable services for transferring pupils with disabilities and eased music and art teacher rules", "student-supports", "core")
add("83:SB403", "Created a metrics subcommittee, expanded competency-based learning, and allowed alternative schedules", "testing-graduation", "core")
add("83:SB411", "Repealed the six-year consultant reviews of district financial management", "spending-oversight", "core")
add("83:SB418", "Pension contribution collections; not K-12", "context", "context")
add("83:SB430", "Would have given tax credits for at-cost starter homes; housing policy, Local School Support Tax touched mechanically", "context", "context")
add("83:SB444", "Required school cellphone policies with progressive discipline and instructional-time limits", "classroom-time-content", "core")
add("83:SB445", "Required archiving and destroying pupil data after graduation", "spending-oversight", "adjacent")
add("83:SB446", "Adjusted work-based learning eligibility and volunteer background checks", "classroom-time-content", "core")
add("83:SB448", "Money to Workforce Connections for a youth program", "context", "context")
add("83:SB460", "Required elementary achievement plans with consequences for principals and created a Public Education Oversight Board", "accountability-governance", "core")
add("83:SB461", "Economic development abatements; not K-12", "context", "context")
add("83:SB468", "Money for charter school pupil transportation", "charters-choice", "adjacent")
add("83:SB470", "Money for the Account for Charter Schools", "charters-choice", "adjacent")
add("83:SB471", "Would have changed how the Governor budgets the State Education Fund baseline", "school-funding", "core")
add("83:SB473", "Money to replace education-department computers and chairs; administration", "spending-oversight", "adjacent")
add("83:SB500", "The biennium K-12 funding act for 2025-2027: per-pupil base and weighted funding", "school-funding", "core")
add("83:SB506", "Money for charter school employee salary increases through the charter authority", "teacher-workforce", "core")
add("83:SCR4", "Declared April 2025 Financial Literacy Month; resolution", "classroom-time-content", "adjacent")
add("83:SCR5", "Antimicrobial resistance resolution; not K-12", "context", "context")
