# Curation entries, session 80 (2019). Written by reading every NELIS
# Overview digest (evidence-curator v2.2 judgment step). Merged into
# curation-map.json by curation-assemble.py.
E = {}

def add(key, topic, theme, rel):
    E[key] = {"plain_topic": topic, "theme": theme, "relevance": rel}

# --- chunk 1 (AB6-AB244) ---
add("80:AB6", "Swapped which state official sits on the STEM and library/literacy councils; not K-12 policy", "context", "context")
add("80:AB32", "Workforce recruitment and training programs for businesses; not K-12", "context", "context")
add("80:AB34", "State Treasurer investment rules, touching the Permanent School Fund only in passing", "context", "context")
add("80:AB35", "Let new schools open as achievement charter schools and set conversion and enrollment rules", "charters-choice", "core")
add("80:AB41", "Fictitious addresses for crime victims; not K-12", "context", "context")
add("80:AB42", "Ordered a State Board subcommittee to study adding substance-abuse lessons to middle and high school health classes", "classroom-time-content", "core")
add("80:AB57", "Would have made some Clark and Washoe school board seats appointed instead of elected", "accountability-governance", "core")
add("80:AB64", "Changed how charter schools are paid for pupils in full-time distance education", "school-funding", "core")
add("80:AB67", "Would have created 'A+' achievement charter schools run by independent administrators", "charters-choice", "core")
add("80:AB72", "Changed who evaluates the principal of a low-performing 'turnaround' school", "accountability-governance", "core")
add("80:AB78", "Abolished the Achievement School District and moved its charter schools to the State Public Charter School Authority", "charters-choice", "core")
add("80:AB88", "Adjusted district enrollment-reporting deadlines and what large districts must report and post online about school allocations", "spending-oversight", "adjacent")
add("80:AB92", "Extended the English Mastery Council and expanded its advice on teaching English learners, with money attached", "student-supports", "core")
add("80:AB99", "Required civics instruction on the founding principles of American government, with biennial reports", "classroom-time-content", "core")
add("80:AB101", "Declaratory-judgment lawsuits against governments; not K-12", "context", "context")
add("80:AB113", "Sales tax on out-of-state firearm transfers; not K-12", "context", "context")
add("80:AB114", "Required schools to report suicide-prevention courses, staff training, and pupil suicide incidents to the state", "student-supports", "core")
add("80:AB123", "Required schools to keep and report records on pupil immunization exemptions and notify parents of outbreaks", "student-supports", "adjacent")
add("80:AB132", "Marijuana screening tests in hiring; not K-12", "context", "context")
add("80:AB136", "Ended the rule that let school and higher-ed construction pay 90 percent of the prevailing wage", "facilities-operations", "adjacent")
add("80:AB144", "Ballot question to exempt diapers from sales tax, amending the Local School Support Tax in parallel; not education policy", "context", "context")
add("80:AB145", "Would have required a police officer in every middle, junior high, and high school and access-control gates on request", "facilities-operations", "core")
add("80:AB146", "Would have created a statewide, independent Nevada Office of the Inspector General to investigate state and local agencies", "spending-oversight", "adjacent")
add("80:AB147", "Let physician assistants and nurse practitioners sign concussion return-to-play clearances; health licensing, not K-12 policy", "context", "context")
add("80:AB151", "Reporting of commercial sexual exploitation of children; child welfare, not school policy", "context", "context")
add("80:AB156", "Required courts to appoint an educational decision maker for children in protection cases", "student-supports", "adjacent")
add("80:AB157", "Had the education department create school materials about human trafficking of children", "student-supports", "adjacent")
add("80:AB159", "Governor's food security council; not K-12", "context", "context")
add("80:AB164", "Marijuana advertising rules; not K-12", "context", "context")
add("80:AB168", "Required a restorative-justice plan before expelling a pupil and limited suspensions for young children", "student-supports", "core")
add("80:AB180", "Set rules for transporting foster and disabled pupils and keeping foster children in their school of origin", "student-supports", "core")
add("80:AB190", "General prevailing-wage rules for public works; not K-12 policy", "context", "context")
add("80:AB194", "Added a pediatric-health member to the Early Childhood Advisory Council and required an annual report", "early-learning-reading", "core")
add("80:AB196", "Would have funded pay incentives for teachers at Title I and underperforming schools", "teacher-workforce", "core")
add("80:AB199", "Let unions and trade groups help schools teach career and technical courses and eased CTE teacher endorsements", "classroom-time-content", "core")
add("80:AB205", "Required school districts to adopt integrated pest-management policies for school grounds", "facilities-operations", "adjacent")
add("80:AB208", "Eased background-check waivers for school volunteers and required certain instruction, including in youth detention facilities", "classroom-time-content", "core")
add("80:AB213", "Restricted driver's licenses for charter school pupils; DMV rule, not education policy", "context", "context")
add("80:AB216", "Database of higher-education funding sources; not K-12", "context", "context")
add("80:AB218", "Revised the education savings account program for private-school costs, with an appropriation", "charters-choice", "core")
add("80:AB219", "Required separate accountability reporting on English learners and corrective plans at low-performing schools", "testing-graduation", "core")
add("80:AB235", "Restructured the Nevada Advisory Commission on Mentoring and gave it education-department support", "student-supports", "adjacent")
add("80:AB237", "Turned teacher reimbursements into an up-front stipend for classroom supplies and widened who gets it", "teacher-workforce", "core")
add("80:AB238", "Added mental health screenings and follow-up monitoring after bullying reports, with public reporting", "student-supports", "core")
add("80:AB240", "Regional growth-management reports in western Nevada; not K-12", "context", "context")
add("80:AB244", "Let school boards convene advisory committees to recommend property taxes for school buildings", "facilities-operations", "adjacent")

# --- chunk 2 (AB248-AB420) ---
add("80:AB248", "Settlement agreement secrecy limits; not K-12", "context", "context")
add("80:AB249", "Land banks for vacant property; not K-12", "context", "context")
add("80:AB253", "Would have created a state program and money to expand prekindergarten and train pre-K teachers", "early-learning-reading", "core")
add("80:AB258", "Let parents enforce special-education due-process decisions through the education department", "student-supports", "core")
add("80:AB261", "Required schools to report training and incidents relating to the personal safety and abuse of children", "student-supports", "adjacent")
add("80:AB275", "Occupational licensing regardless of immigration status; touches teacher licensing only in passing", "context", "context")
add("80:AB276", "Created the state Teacher Recruitment and Retention Advisory Task Force, with money attached", "teacher-workforce", "core")
add("80:AB277", "Would have required every district to bargain a program raising teacher and support-staff salaries and reserve money for it", "teacher-workforce", "core")
add("80:AB281", "Immigration holds by police, including school police; not education policy", "context", "context")
add("80:AB284", "Opened the alternative teaching license route to special-education teachers of deaf and visually impaired pupils", "teacher-workforce", "core")
add("80:AB289", "Ended automatic third-grade retention under Read by Grade 3, requiring intensive reading help instead", "early-learning-reading", "core")
add("80:AB293", "Would have banned suspending young pupils for defiance or disruption", "student-supports", "core")
add("80:AB294", "Made schools accept transfer credits of pupils with unstable housing and eased their graduation requirements", "testing-graduation", "core")
add("80:AB295", "Would have replaced the AIDS/reproduction course with evidence-based sexuality education and added pupils to the advisory committee", "classroom-time-content", "core")
add("80:AB296", "Would have created a Nevada Office of the Inspector General inside the Department of Administration to investigate agencies", "spending-oversight", "adjacent")
add("80:AB304", "Required class-size reduction plans with ratio-variance requests and annual public posting of class sizes", "classroom-time-content", "core")
add("80:AB308", "Payroll-tax credit for employers paying for employee courses; not K-12", "context", "context")
add("80:AB309", "Would have rebuilt the school funding formula around all state aid and required districts to reserve money for negotiated raises", "school-funding", "core")
add("80:AB312", "Limited how much test-participation counts in school star ratings and required parent notices about exams", "testing-graduation", "core")
add("80:AB314", "Let schools count up to three 'digital days' of remote instruction when buildings close", "classroom-time-content", "core")
add("80:AB318", "Required districts and charters to adopt policies promoting work-based learning and apprenticeship preparation", "classroom-time-content", "core")
add("80:AB319", "Criminal-history petitions for occupational licenses; not K-12 policy", "context", "context")
add("80:AB322", "Money for Clark County juvenile assessment centers; justice system, not school policy", "context", "context")
add("80:AB331", "Created an outdoor education grant program aimed at disadvantaged and at-risk pupils", "classroom-time-content", "core")
add("80:AB332", "Would have given school staff legal immunity for using force to stop harm and piloted body cameras in Clark County", "facilities-operations", "adjacent")
add("80:AB340", "Let schools stock opioid-overdose antidotes under a health professional's order", "student-supports", "adjacent")
add("80:AB341", "Gave nationally certified school nurses the same 5 percent pay bump as certified teachers", "teacher-workforce", "core")
add("80:AB342", "Added district liaisons for military children under the interstate education compact", "student-supports", "adjacent")
add("80:AB343", "Required staff training on pupil mental health and created the Task Force on the Mental Health of Children", "student-supports", "core")
add("80:AB350", "Would have restructured higher-education administration; not K-12", "context", "context")
add("80:AB353", "Recycling requirements for public agencies including school districts; not education policy", "context", "context")
add("80:AB359", "Would have built statewide and regional networks to broker work-based learning programs with employers", "classroom-time-content", "core")
add("80:AB363", "DMV fee waivers for homeless youth; not school policy", "context", "context")
add("80:AB371", "Public-records request reporting; not K-12", "context", "context")
add("80:AB378", "Added mental-illness response procedures to school crisis plans and revised emergency admissions for children", "student-supports", "core")
add("80:AB380", "Would have made reported bullying victims immediately eligible for private-school education savings accounts", "charters-choice", "core")
add("80:AB383", "Student-loan ombudsman for borrowers; higher-education finance, not K-12", "context", "context")
add("80:AB385", "Southern Nevada Enterprise Community economic development; not K-12", "context", "context")
add("80:AB387", "Task force to keep families from giving up custody to get children's mental health services; child welfare with school ties", "student-supports", "adjacent")
add("80:AB392", "Would have certified employers for work-based learning and covered pupil insurance in such programs", "classroom-time-content", "core")
add("80:AB396", "Would have made confirmed bullying victims immediately eligible for education savings accounts", "charters-choice", "core")
add("80:AB400", "Would have shielded the Local School Support Tax from economic-development abatements and tightened repeat abatements", "school-funding", "adjacent")
add("80:AB405", "Bond-financed student loans for job training; not K-12", "context", "context")
add("80:AB409", "Marijuana consumption lounges; not K-12", "context", "context")
add("80:AB411", "Civil penalties for traffic violations; not K-12", "context", "context")
add("80:AB420", "Criminal forfeiture procedures; not K-12", "context", "context")

# --- chunk 3 (AB430-SB184) ---
add("80:AB430", "Interim study of maternal, infant, and early childhood home visitation services", "early-learning-reading", "adjacent")
add("80:AB434", "Fines and traffic offense collections; not K-12", "context", "context")
add("80:AB435", "Moved detained youths who assault their teachers to approved distance education courses", "student-supports", "adjacent")
add("80:AB442", "Payroll-tax credit for employers funding employee instruction; not K-12", "context", "context")
add("80:AB445", "Online marketplace sales-tax collection; not K-12", "context", "context")
add("80:AB459", "Made the state's education accountability data searchable by category", "spending-oversight", "core")
add("80:AB460", "Cut pupil-growth data from 40 to 10 percent of teacher and administrator evaluations", "accountability-governance", "core")
add("80:AB461", "Higher-education liaison and fee waivers for homeless students; postsecondary, not K-12", "context", "context")
add("80:AB462", "Required a statewide plan to manage charter school growth and notice before schools open or expand", "charters-choice", "core")
add("80:AB464", "Sports eligibility for returning foreign-exchange pupils; interscholastic rules, not education outcomes", "context", "context")
add("80:AB475", "Set training standards for school boards and charter boards, with public completion announcements", "accountability-governance", "core")
add("80:AB486", "Created the state Division of Outdoor Recreation; not K-12", "context", "context")
add("80:AB490", "Required schools to collect and report pupil discipline data broken out by student group", "student-supports", "core")
add("80:AB491", "Would have added two governor-appointed finance experts to the Clark and Washoe school boards", "accountability-governance", "core")
add("80:AB543", "The state general appropriations act for 2019-2021, funding all of state government including schools", "school-funding", "adjacent")
add("80:SB14", "Governor's removal of board appointees; not K-12", "context", "context")
add("80:SB26", "Shielded a slice of school district ending fund balances from collective-bargaining arbitration", "teacher-workforce", "adjacent")
add("80:SB41", "Reworked teacher licensing: dropped the special-qualifications license and revised the standards commission", "teacher-workforce", "core")
add("80:SB52", "Funded scholarships for teachers seeking business-and-industry endorsements", "teacher-workforce", "core")
add("80:SB57", "Made public school blueprints confidential except for safety agencies", "facilities-operations", "adjacent")
add("80:SB69", "Standardized emergency response plan updates for schools and others", "facilities-operations", "adjacent")
add("80:SB79", "Required a statewide policy and training for managing chronic absenteeism", "student-supports", "core")
add("80:SB80", "Renamed Safe-to-Tell as SafeVoice and created Handle with Care alerts when children face trauma", "student-supports", "core")
add("80:SB82", "College savings plan governance; higher-education finance, not K-12", "context", "context")
add("80:SB84", "Would have created a grant program supporting prekindergarten programs statewide", "early-learning-reading", "core")
add("80:SB89", "Required accountability reports broken out by pupil group, school-climate plans, and school safety changes", "testing-graduation", "core")
add("80:SB90", "Child lead testing and diaper assistance; health policy, not K-12", "context", "context")
add("80:SB91", "Created the Commission on Innovation and Excellence in Education to benchmark Nevada against top systems", "accountability-governance", "core")
add("80:SB99", "Created an advisory committee to design a tiered career pathway for teachers", "teacher-workforce", "core")
add("80:SB100", "Expedited teaching licenses for military spouses and credited military experience", "teacher-workforce", "core")
add("80:SB101", "Adjusted the timeline for adopting the school-funding equity allocation model", "school-funding", "core")
add("80:SB105", "Would have made some Clark and Washoe school board seats appointed instead of elected", "accountability-governance", "core")
add("80:SB106", "Let schools reduce required textbook-and-supplies spending when materials are free", "spending-oversight", "adjacent")
add("80:SB109", "Would have required cameras in self-contained special-education classrooms", "student-supports", "core")
add("80:SB111", "Changed which school-district money is on the table in collective bargaining", "teacher-workforce", "adjacent")
add("80:SB126", "Ended the five-year reappointment cycle for postprobationary school administrators", "accountability-governance", "core")
add("80:SB133", "Money for educational leadership training programs", "teacher-workforce", "core")
add("80:SB139", "Would have funded a grant program teaching leadership skills to younger pupils", "classroom-time-content", "core")
add("80:SB142", "Added counselors and school police to school safety teams and revised the SafeVoice program", "student-supports", "core")
add("80:SB147", "Made schools give homeless and foster pupils partial credit and flexible diplomas", "testing-graduation", "core")
add("80:SB153", "Collective-bargaining procedures including school district negotiations", "teacher-workforce", "adjacent")
add("80:SB159", "Required school sun-safety policies letting pupils carry sunscreen", "student-supports", "adjacent")
add("80:SB162", "Blockchain records; not K-12", "context", "context")
add("80:SB171", "Health workforce data collection; not K-12", "context", "context")
add("80:SB178", "Council on Food Security; not K-12", "context", "context")
add("80:SB184", "Child-abuse report handling, touching school reporting duties; child welfare, not education policy", "context", "context")

# --- chunk 4 (SB185-SB402) ---
add("80:SB185", "Loosened fingerprint background checks for supervised school volunteers", "facilities-operations", "adjacent")
add("80:SB188", "Would have required every district and school to publish a plain explanation of each expenditure and budget per-pupil", "spending-oversight", "core")
add("80:SB190", "2020 census outreach; not K-12", "context", "context")
add("80:SB191", "Would have required every public school to keep a standards-based library with a teacher librarian", "classroom-time-content", "core")
add("80:SB193", "Money for history, law, and civics education programs", "classroom-time-content", "core")
add("80:SB194", "Matched-savings accounts for low-income households; not K-12", "context", "context")
add("80:SB202", "Required annual public reporting on pupils with disabilities and parental information on services", "student-supports", "core")
add("80:SB203", "Hearing aids for children; health services, school-adjacent", "context", "context")
add("80:SB204", "Required suicide-prevention policies for every school and a model response plan", "student-supports", "core")
add("80:SB216", "Established the autism commission in statute; health policy with school ties", "context", "context")
add("80:SB227", "Required a standard template for reporting school-by-school spending and what a budget should buy", "spending-oversight", "core")
add("80:SB231", "Public-works labor records; not K-12", "context", "context")
add("80:SB233", "Eased conditions for emergency school-repair grants to districts", "facilities-operations", "adjacent")
add("80:SB238", "Marijuana licensing; not K-12", "context", "context")
add("80:SB239", "Put bullying victims' interests first in investigations and adjusted timelines", "student-supports", "core")
add("80:SB240", "Dropped the school-law and constitution training requirements for new teachers", "teacher-workforce", "core")
add("80:SB245", "Tort damages cap against governments; not K-12", "context", "context")
add("80:SB249", "Would have required school libraries with licensed school librarians in every public school", "classroom-time-content", "core")
add("80:SB253", "Changed suspension and dismissal procedures for licensed school employees", "teacher-workforce", "core")
add("80:SB262", "Asthma drug price reporting; not K-12", "context", "context")
add("80:SB266", "Mental-health first-aid training program; statewide health, not school-specific", "context", "context")
add("80:SB267", "Required schools to identify and weigh social and environmental factors affecting pupils", "student-supports", "core")
add("80:SB282", "Crisis-center liability; not K-12", "context", "context")
add("80:SB285", "Grants up to $500,000 per building for school security improvements, with money attached", "facilities-operations", "adjacent")
add("80:SB295", "Created the National Guard Youth Challenge school for dropouts and at-risk youth", "student-supports", "core")
add("80:SB296", "Allowed teaching licenses by endorsement for teachers licensed in other countries", "teacher-workforce", "core")
add("80:SB299", "Electric vehicle infrastructure; school-bus mention only", "context", "context")
add("80:SB302", "Government data security; not K-12", "context", "context")
add("80:SB303", "Money for pay incentives for nationally certified teachers at Title I schools", "teacher-workforce", "core")
add("80:SB305", "Would have let counties raise sales tax for pre-K and other programs and tapped marijuana tax for achievement", "school-funding", "core")
add("80:SB313", "Built a computer-science resource repository, teacher reimbursements, and a technology account", "classroom-time-content", "core")
add("80:SB314", "Created the State Seal of Financial Literacy, an advisory council, and teaching endorsements", "classroom-time-content", "core")
add("80:SB315", "Rare-disease council and childhood health awareness; not education policy", "context", "context")
add("80:SB317", "Funded juvenile assessment centers to support pupils after adverse childhood experiences, $16 million", "student-supports", "adjacent")
add("80:SB318", "Created school threat assessment teams and district safety specialists", "facilities-operations", "core")
add("80:SB319", "Defined school counselor, psychologist, and social worker duties and pushed full-time counselors where money allows", "student-supports", "core")
add("80:SB320", "Required schools to identify pupils for more rigorous core courses", "classroom-time-content", "core")
add("80:SB321", "Would have abolished the Achievement School District and reverted its schools", "charters-choice", "core")
add("80:SB324", "Made teacher school-supplies money easier to disburse and roll over", "teacher-workforce", "core")
add("80:SB330", "Electric vehicle infrastructure incentives; school buses mentioned only", "context", "context")
add("80:SB332", "Ordered an interim study on safe and respectful learning environments free of bullying", "student-supports", "core")
add("80:SB343", "Set training and reporting standards for school boards, with spending data added to the accountability system", "accountability-governance", "core")
add("80:SB349", "Would have revived and funded education savings accounts under a new Office of Educational Choice", "charters-choice", "core")
add("80:SB351", "Ordered independent evaluations of the private-school Opportunity Scholarship program and eased disability eligibility", "charters-choice", "core")
add("80:SB372", "Would have moved school psychologist and counselor licensing to health boards", "teacher-workforce", "core")
add("80:SB402", "STEM support license plates; not education policy", "context", "context")

# --- chunk 5 (SB403-SCR1) ---
add("80:SB403", "Required schools to disclose which online services get pupil data before pupils use classroom technology", "classroom-time-content", "core")
add("80:SB404", "Would have added tax-credit scholarships for early childhood and career-technical programs", "charters-choice", "core")
add("80:SB414", "Expanded the Guinn Memorial scholarship for future teachers; postsecondary scholarship", "teacher-workforce", "adjacent")
add("80:SB441", "Created rules for charter schools operating entirely as distance education", "charters-choice", "core")
add("80:SB444", "Money for prekindergarten enrollment costs", "early-learning-reading", "core")
add("80:SB445", "Would have set a $45,000 minimum teacher salary and grants for relocating teachers", "teacher-workforce", "core")
add("80:SB447", "Medical equipment sales-tax exemption; Local School Support Tax amended mechanically", "context", "context")
add("80:SB451", "Let charter contracts renew for three to ten years instead of a fixed six", "charters-choice", "core")
add("80:SB458", "Money for nonprofit school-garden programs at Title I schools", "student-supports", "adjacent")
add("80:SB465", "Let redevelopment agencies pass school property-tax increments back to districts", "school-funding", "adjacent")
add("80:SB467", "Extended Zoom (English learner) and Victory (poverty) school programs, with money attached", "school-funding", "core")
add("80:SB468", "Exempted private pre-K programs taking no public money from child-care licensing", "early-learning-reading", "adjacent")
add("80:SB469", "Tuned Clark County's site-based school precinct system: utilities, supervision spans, and allocations", "accountability-governance", "core")
add("80:SB475", "Cut pupil performance to 15 percent of educator evaluations and required annual evaluation of other licensed staff", "accountability-governance", "core")
add("80:SB476", "Built the computer-science instruction repository and grant program", "classroom-time-content", "core")
add("80:SB478", "Peer-to-peer car sharing; not K-12", "context", "context")
add("80:SB485", "Limited reimbursements to hospitals schooling resident child patients", "school-funding", "adjacent")
add("80:SB503", "Money to continue the Nevada Promise college scholarship; postsecondary", "context", "context")
add("80:SB505", "Money to settle the district-of-residence funding adjustment among districts", "school-funding", "adjacent")
add("80:SB520", "Supplemental money to the Distributive School Account for unanticipated enrollment growth", "school-funding", "core")
add("80:SB523", "Supplemental money for a staffing shortfall in state literacy programs", "early-learning-reading", "core")
add("80:SB528", "Brain-health center appropriations; not K-12", "context", "context")
add("80:SB538", "Office for New Americans; not K-12", "context", "context")
add("80:SB543", "Created the State Education Fund and the Pupil-Centered Funding Plan, replacing the 52-year-old Nevada Plan formula", "school-funding", "core")
add("80:SB545", "Redirected the 10 percent retail marijuana tax from the Rainy Day Fund to the school account", "school-funding", "core")
add("80:SB549", "Adjusted which assessments drive New Nevada Education Funding Plan allocations", "school-funding", "core")
add("80:SB551", "Kept payroll-tax rates from falling and steered money to schools and safety programs", "school-funding", "adjacent")
add("80:SB555", "The biennium K-12 funding act: apportioned the school account, class-size reduction, and categorical programs", "school-funding", "core")
add("80:SCR1", "Interim energy study; not K-12", "context", "context")
