#!/usr/bin/env python3
"""Assemble curation-map.json for the NH property-taxes set (the judgment step).

Each entry: plain_topic (one plain sentence), theme (one of THEMES), and
relevance tier (core / adjacent / context). Context bills stay in the set for
audit but are excluded from headline numbers. Dispositions/stages are merged
in from dispositions.json (evidence-backed; nothing invented here).

The per-bill judgments live in the E dict below, keyed "YEAR:BILL" ->
(plain_topic, theme_key, relevance); this script validates the set is fully
covered and merges dispositions in.

Run from repo root:
  python3 working/new-hampshire/property-taxes/build-curation.py
"""

from __future__ import annotations

import json
from pathlib import Path

W = Path("working/new-hampshire/property-taxes")

THEMES = {
    "T1": "Property tax relief: exemptions, credits, and deferrals",
    "T2": "Assessment, abatement, and property tax administration",
    "T3": "The statewide education property tax and school funding",
    "T4": "State business taxes: BPT and BET",
    "T5": "The interest and dividends tax",
    "T6": "Meals and rooms, gaming, and other existing revenue streams",
    "T7": "New or broad-based taxes and constitutional tax limits",
    "T8": "Municipal revenue, state aid, and state budget mechanics",
    "T9": "Current use, timber, utility, and other property-tax bases",
    "T10": "School district and municipal consolidation or cooperation",
    "T11": "Tax caps and local budget limits",
    "CTX": "Context: not primarily a property-tax or revenue bill",
}


# (plain_topic, theme_key, relevance)
E = {
    # ---------------- 2020 ----------------
    "2020:CACR1": ("Constitutional amendment directing a share of liquor commission revenue to alcohol and drug abuse prevention.", "T6", "adjacent"),
    "2020:CACR17": ("Constitutional amendment allowing a new state broad-based tax only if it is used to reduce property taxes.", "T7", "core"),
    "2020:HB1110": ("Would have applied the meals and rooms tax to certain Dartmouth College property.", "T6", "adjacent"),
    "2020:HB1125": ("Would have let municipalities exempt volunteer firefighters and emergency medical personnel from property taxes.", "T1", "core"),
    "2020:HB1139": ("Would have studied eligibility for the property tax credits, exemptions, and deferrals available to people with limited income.", "T1", "core"),
    "2020:HB114": ("Would have barred the state from joining interstate sales-tax collection agreements.", "T7", "adjacent"),
    "2020:HB1154": ("Would have let municipalities exclude retirement-account principal from the asset tests for property tax exemptions.", "T1", "core"),
    "2020:HB1155": ("Would have exempted certain residential cutting from the timber tax.", "T9", "adjacent"),
    "2020:HB1160": ("Would have let municipalities collect an occupancy fee from local room-rental operators.", "T8", "core"),
    "2020:HB1161": ("Would have set electronic-filing rules for meals and rooms returns and interest on state tax payments.", "T6", "adjacent"),
    "2020:HB117": ("Would have raised the exemptions under the interest and dividends tax while trimming business R&D credits.", "T5", "core"),
    "2020:HB1197": ("Would have exempted disabled veterans from paying property taxes.", "T1", "core"),
    "2020:HB1200": ("Would have delayed the single sales factor under the business taxes and changed the tax expenditure report.", "T4", "adjacent"),
    "2020:HB1210": ("Would have created a property tax exemption for energy storage systems.", "T1", "adjacent"),
    "2020:HB1237": ("Would have studied utility companies' reporting for the property tax valuation of utility assets.", "T9", "adjacent"),
    "2020:HB1248": ("Would have adjusted the community revitalization (RSA 79-E) property tax relief incentives.", "T1", "adjacent"),
    "2020:HB1291": ("Homestead food licensing; matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2020:HB130": ("Extended property tax relief to totally and permanently disabled veterans (became law).", "T1", "core"),
    "2020:HB1311": ("Would have changed semi-annual and quarterly property tax collection in certain municipalities.", "T2", "adjacent"),
    "2020:HB1368": ("Cooperative school board vacancy rules; governance housekeeping, not school-district finance.", "CTX", "context"),
    "2020:HB1392": ("Federal tax lien filing procedure; recording mechanics, not New Hampshire tax policy.", "CTX", "context"),
    "2020:HB1406": ("Would have changed the property tax exemptions for solar and wind energy systems.", "T1", "adjacent"),
    "2020:HB1421": ("Would have created a commission to study the equalization rate used in property tax abatement calculations.", "T2", "core"),
    "2020:HB1423": ("Would have changed reporting on education tax credit scholarships.", "T4", "adjacent"),
    "2020:HB1467": ("Would have changed how commercial and residential property are taxed relative to each other.", "T2", "core"),
    "2020:HB1474": ("Would have created business profits tax deductions for federal Opportunity Zone investments.", "T4", "adjacent"),
    "2020:HB1477": ("Would have studied the impact of tobacco taxes on tobacco use and cessation programs.", "T6", "adjacent"),
    "2020:HB1490": ("Would have studied the property taxation of owners on private roads.", "T2", "adjacent"),
    "2020:HB1492": ("Would have created a tax on retail sales of certain electronic devices to fund education.", "T7", "core"),
    "2020:HB1510": ("Would have let municipalities adopt a property tax exemption for accessory dwelling units.", "T1", "adjacent"),
    "2020:HB1533": ("Would have limited property tax increases for certain persons.", "T1", "core"),
    "2020:HB1567": ("Would have required worldwide combined reporting for unitary businesses under the business profits tax.", "T4", "core"),
    "2020:HB1579": ("Would have changed collection of the meals and rooms tax for short-term rentals.", "T6", "adjacent"),
    "2020:HB1631": ("Would have changed the taxation of certain hydro-electric generation facilities.", "T9", "adjacent"),
    "2020:HB1652": ("Would have extended the meals and rooms tax to ski lift tickets to fund a scholarship program.", "T6", "adjacent"),
    "2020:HB1661": ("Would have changed the property tax exemption for water and air pollution control facilities.", "T1", "adjacent"),
    "2020:HB1691": ("Would have changed kindergarten adequate education grants.", "T3", "adjacent"),
    "2020:HB1699": ("Would have created a tax on electronic cigarettes.", "T6", "core"),
    "2020:HB176": ("Would have funded school building aid grants with an appropriation.", "T3", "core"),
    "2020:HB184": ("Would have counted kindergarteners fully in enrollment and ended keno-dependent kindergarten funding.", "T3", "adjacent"),
    "2020:HB265": ("Would have addressed New Hampshire businesses collecting other states' sales taxes.", "T7", "adjacent"),
    "2020:HB274": ("Would have extended the meals and rooms tax to internet facilitators of vehicle rentals and room bookings.", "T6", "adjacent"),
    "2020:HB352": ("Would have appropriated wastewater state aid grants for municipal projects.", "T8", "core"),
    "2020:HB479": ("Would have changed eligibility for the low and moderate income homeowners property tax relief program.", "T1", "core"),
    "2020:HB482": ("Would have changed the revenue stabilization (rainy day) account rules.", "T8", "adjacent"),
    "2020:HB497": ("Would have restored a state share of local employers' retirement system contributions.", "T8", "core"),
    "2020:HB551": ("Would have created a school funding commission with an appropriation.", "T3", "core"),
    "2020:HB623": ("Would have changed the business profits and business enterprise tax rates.", "T4", "core"),
    "2020:HB653": ("Would have changed meals and rooms tax payment for short-term rentals.", "T6", "adjacent"),
    "2020:HB678": ("Would have required full state funding of the cost of an adequate education.", "T3", "core"),
    "2020:HB680": ("Would have redefined 'tobacco product' for the tobacco tax and retail licensing.", "T6", "adjacent"),
    "2020:HB686": ("Would have rewritten interim adequacy funding and extended the interest and dividends tax to capital gains.", "T3", "core"),
    "2020:HB698": ("Would have pushed back on foreign jurisdictions compelling New Hampshire businesses to collect their sales taxes.", "T7", "adjacent"),
    "2020:HB709": ("Would have changed the formula for determining adequate education funding.", "T3", "core"),
    "2020:HB722": ("Would have legalized and taxed retail marijuana; sent to interim study.", "T7", "adjacent"),
    "2020:HR16": ("House resolution affirming state revenue estimates for fiscal 2020-2021.", "T8", "adjacent"),
    "2020:SB223": ("Would have raised the minimum gross business income requiring a business profits tax return.", "T4", "adjacent"),
    "2020:SB424": ("Would have changed the solar energy property tax exemption.", "T1", "adjacent"),
    "2020:SB474": ("Would have changed the income tax on interest and dividends.", "T5", "core"),
    "2020:SB475": ("Would have let municipalities adopt a property tax credit for densely-built workforce housing.", "T1", "adjacent"),
    "2020:SB483": ("Would have changed the property tax exemption for educational organizations.", "T1", "adjacent"),
    "2020:SB484": ("Would have created a commission to study payments in lieu of taxes (PILOTs).", "T8", "core"),
    "2020:SB511": ("Would have changed the formula used to determine current use tax rates.", "T9", "core"),
    "2020:SB516": ("Would have created a property tax credit for active duty military personnel.", "T1", "core"),
    "2020:SB530": ("Would have changed property tax exemptions for renewable energy systems.", "T1", "adjacent"),
    "2020:SB538": ("Would have created a commission to study property tax exemptions for charitable organizations.", "T1", "core"),
    "2020:SB558": ("Extended the reporting date of the commission to study school funding (became law).", "T3", "adjacent"),
    "2020:SB560": ("Would have required keno adoption questions to be placed on the warrant.", "T6", "adjacent"),
    "2020:SB562": ("Would have created property tax relief for designated residential revitalization zones.", "T1", "adjacent"),
    "2020:SB583": ("Would have added climate science to the adequate education criteria; education content, not funding.", "CTX", "context"),
    "2020:SB616": ("Would have studied the meals and rooms tax distribution formula to municipalities.", "T8", "core"),
    "2020:SB661": ("Would have adjusted economic revitalization zone tax credits and the graduate retention partnership.", "T4", "adjacent"),
    "2020:SB662": ("Would have exempted medical expenses under the interest and dividends tax.", "T5", "core"),
    "2020:SB663": ("Would have created a business tax credit for graduate-retention stipend payments.", "T4", "adjacent"),
    "2020:SB757": ("Would have created a local option for sports book retail locations.", "T6", "adjacent"),
    "2020:SB762": ("Opioid settlement trust fund creation; matched by 'abatement' but not tax policy.", "CTX", "context"),
    "2020:SB93": ("Would have applied the communications services tax to prepaid wireless and VoIP services.", "T6", "adjacent"),
    "2020:SB95": ("Would have created a working families property tax refund program.", "T1", "core"),
    # ---------------- 2021 ----------------
    "2021:CACR1": ("Constitutional amendment to prohibit an income tax on earned personal income.", "T7", "core"),
    "2021:CACR2": ("Constitutional amendment to prohibit any broad-based sales tax.", "T7", "core"),
    "2021:CACR3": ("Constitutional amendment to let tax money fund religious educational institutions.", "T3", "adjacent"),
    "2021:CACR9": ("Constitutional amendment capping municipal property tax increases at 2 percent a year (1 percent for disabled and senior citizens).", "T11", "core"),
    "2021:HB10": ("Same bill as 2022 HB10 (business tax rates; carried across the biennium); see the 2022 record.", "T4", "core"),
    "2021:HB102": ("Same bill as 2022 HB102 (worldwide combined reporting; carried across the biennium); see the 2022 record.", "T4", "core"),
    "2021:HB110": ("Same bill as 2022 HB110 (adequate education grant distribution; carried across the biennium); see the 2022 record.", "T3", "core"),
    "2021:HB126": ("Required notice to mortgage holders when a property tax lien is executed (became law).", "T2", "adjacent"),
    "2021:HB15": ("Extended the meals and rooms tax to internet booking facilitators for vehicle rentals and rooms (became law).", "T6", "adjacent"),
    "2021:HB152": ("Changed how costs are apportioned among towns in cooperative school districts (became law).", "T10", "core"),
    "2021:HB154": ("Adjusted the community revitalization (RSA 79-E) tax relief incentives (became law).", "T1", "adjacent"),
    "2021:HB181": ("Would have created a local option for sports book retail locations.", "T6", "adjacent"),
    "2021:HB2": ("The 2021 omnibus budget trailer itself; its tax and revenue sections are analyzed section-by-section in the HB2 analysis and excluded from bill counts to avoid double-counting.", "CTX", "context"),
    "2021:HB210": ("Same bill as 2022 HB210 (I&D exemptions / R&D credits; carried across the biennium); see the 2022 record.", "T5", "core"),
    "2021:HB214": ("Same bill as 2022 HB214 (school building aid; carried across the biennium); see the 2022 record.", "T3", "core"),
    "2021:HB242": ("Would have changed the content of an adequate education; vetoed.", "T3", "adjacent"),
    "2021:HB243": ("Standardized municipal budget forms and estimates of expenditures and revenues (became law).", "T8", "adjacent"),
    "2021:HB252": ("Same bill as 2022 HB252 (child care business tax credit study; carried across the biennium); see the 2022 record.", "T4", "adjacent"),
    "2021:HB274": ("Would have restored a state share of local employers' retirement system contributions.", "T8", "core"),
    "2021:HB281": ("Would have delayed the single sales factor under the business taxes and changed the tax expenditure report.", "T4", "adjacent"),
    "2021:HB306": ("Set revenue-estimating rules while operating under COVID-19 emergency orders (became law).", "T8", "adjacent"),
    "2021:HB314": ("Same bill as 2022 HB314 (homestead food licensure; carried across the biennium); see the 2022 record.", "CTX", "context"),
    "2021:HB324": ("Updated the Department of Revenue Administration's administration of certain state taxes (became law).", "T2", "adjacent"),
    "2021:HB353": ("Same bill as 2022 HB353 (I&D credit for out-of-state tax paid; carried across the biennium); see the 2022 record.", "T5", "core"),
    "2021:HB354": ("Created the local option for sports betting retail locations (became law).", "T6", "adjacent"),
    "2021:HB355": ("Same bill as 2022 HB355 (keno; carried across the biennium); see the 2022 record.", "T6", "adjacent"),
    "2021:HB383": ("Allowed quarterly or semi-annual property tax collection in certain municipalities (became law).", "T2", "adjacent"),
    "2021:HB400": ("Same bill as 2022 HB400 (foreign sales tax collection; carried across the biennium); see the 2022 record.", "T7", "adjacent"),
    "2021:HB410": ("Same bill as 2022 HB410 (utility assessing study; carried across the biennium); see the 2022 record.", "T9", "adjacent"),
    "2021:HB411": ("Created the commission to study the equalization rate used in property tax abatements (became law).", "T2", "core"),
    "2021:HB415": ("Would have changed municipal estimates of expenditures and revenues.", "T8", "adjacent"),
    "2021:HB464": ("Extended and adjusted the commission to study school funding (became law).", "T3", "adjacent"),
    "2021:HB467": ("Would have changed current use tax rate eligibility.", "T9", "adjacent"),
    "2021:HB486": ("Expanded eligibility for the low and moderate income homeowners property tax relief program (became law).", "T1", "core"),
    "2021:HB504": ("Same bill as 2022 HB504 (SWEPT and homeowner relief; carried across the biennium); see the 2022 record.", "T3", "core"),
    "2021:HB528": ("Would have required electronic filing of state tax returns.", "T2", "adjacent"),
    "2021:HB533": ("Created an investigation and compliance division in the lottery commission (became law).", "T6", "adjacent"),
    "2021:HB552": ("Would have changed property tax valuation procedures.", "T2", "core"),
    "2021:HB568": ("Same bill as 2022 HB568 (I&D exemption increase and 2025 repeal; carried across the biennium); see the 2022 record.", "T5", "core"),
    "2021:HB594": ("Same bill as 2022 HB594 (school building aid program; carried across the biennium); see the 2022 record.", "T3", "core"),
    "2021:HB608": ("Same bill as 2022 HB608 (adequacy formula; carried across the biennium); see the 2022 record.", "T3", "core"),
    "2021:HB613": ("Same bill as 2022 HB613 (special education state aid; carried across the biennium); see the 2022 record.", "T3", "adjacent"),
    "2021:HB623": ("Same bill as 2022 HB623 (education funding; carried across the biennium); see the 2022 record.", "T3", "core"),
    "2021:HB64": ("Enabled voluntary payment-in-lieu-of-taxes agreements for renewable generation facilities (became law).", "T9", "core"),
    "2021:HCR3": ("Would have declared the Claremont school-funding mandates non-binding on the legislature.", "T3", "core"),
    "2021:HR11": ("House resolution affirming revenue estimates for fiscal 2021-2023.", "T8", "adjacent"),
    "2021:SB101": ("Raised the minimum gross business income requiring a business profits tax return (became law).", "T4", "adjacent"),
    "2021:SB102": ("Omnibus property taxation law, including community revitalization (79-E) relief for housing development (became law).", "T1", "core"),
    "2021:SB118": ("Would have enacted the 'property tax relief act of 2021'.", "T1", "core"),
    "2021:SB128": ("Would have temporarily changed operator compensation under the meals and rooms tax.", "T6", "adjacent"),
    "2021:SB13": ("Would have adopted an omnibus package of state tax and fee changes.", "T6", "adjacent"),
    "2021:SB135": ("Same bill as 2022 SB135 (adequacy cost calculation; carried across the biennium); see the 2022 record.", "T3", "core"),
    "2021:SB145": ("Same bill as 2022 SB145 (temporary school funding formula change; carried across the biennium); see the 2022 record.", "T3", "core"),
    "2021:SB158": ("Would have changed the formula for funding an adequate education.", "T3", "core"),
    "2021:SB3": ("Excluded forgiven federal Paycheck Protection Program loans from taxable business profits (became law).", "T4", "core"),
    "2021:SB48": ("Changed the formula used to determine current use tax rates (became law).", "T9", "core"),
    "2021:SB52": ("Clarified city charter provisions for tax caps (became law).", "T11", "core"),
    "2021:SB53": ("Same bill as 2022 SB53 (carried across the biennium; introduced as a community preservation surcharge, amended into a DRA records bill); see the 2022 record.", "T8", "adjacent"),
    "2021:SB72": ("Would have restored a state share of retirement system contributions for local employers.", "T8", "core"),
    "2021:SB82": ("Would have funded kindergarten adequate education grants with an appropriation.", "T3", "adjacent"),
    "2021:SB99": ("Would have raised the share of meals and rooms tax revenue distributed to municipalities.", "T8", "core"),
    # ---------------- 2022 ----------------
    "2022:HB10": ("Would have changed the business profits and business enterprise tax rates.", "T4", "core"),
    "2022:HB102": ("Created a commission to study worldwide combined reporting for unitary businesses under the business profits tax (became law).", "T4", "core"),
    "2022:HB1040": ("Road-toll alternatives study commission; highway-fund transportation revenue, kept for audit.", "CTX", "context"),
    "2022:HB1055": ("Would have changed the property tax exemption for people with disabilities and people who are deaf or severely hearing impaired.", "T1", "core"),
    "2022:HB1056": ("Would have changed the veterans' property tax credits.", "T1", "core"),
    "2022:HB1057": ("Would have changed the elderly property tax exemption.", "T1", "core"),
    "2022:HB1063": ("Technical tax-administration changes for the Department of Revenue Administration, plus county redevelopment district bonds (became law).", "T2", "adjacent"),
    "2022:HB1097": ("Shielded New Hampshire residents working remotely for out-of-state employers from other states' income taxes (became law).", "T7", "adjacent"),
    "2022:HB110": ("Would have changed the distribution of adequate education grants.", "T3", "core"),
    "2022:HB1183": ("Would have changed how property taxes are calculated for residents 75 and older.", "T1", "core"),
    "2022:HB1189": ("Would have allowed voluntary donations to municipalities or the state to fund projects or reduce taxes.", "T8", "adjacent"),
    "2022:HB1194": ("Would have changed the procedure for overriding a local tax cap.", "T11", "core"),
    "2022:HB1204": ("Would have cut the meals and rooms tax rate while raising the municipal share of its revenue.", "T6", "core"),
    "2022:HB1221": ("Cut the business profits tax rate to 7.5 percent and paid municipalities a one-time amount equal to 7.5 percent of their retirement contributions (became law).", "T4", "core"),
    "2022:HB1289": ("Would have let certain homeowners apply for abatements of prior years' taxes.", "T2", "adjacent"),
    "2022:HB1298": ("Would have changed eligibility for the education tax credit.", "T4", "adjacent"),
    "2022:HB1338": ("Would have studied a tax on manufacturers based on single-use product disposal costs.", "T7", "adjacent"),
    "2022:HB1342": ("Would have changed municipal charter provisions for tax caps.", "T11", "core"),
    "2022:HB1350": ("Would have changed the procedure for valuing property for property tax purposes.", "T2", "core"),
    "2022:HB1365": ("Would have let towns and cities tax residential and non-residential property at different rates.", "T2", "core"),
    "2022:HB1366": ("Would have changed cooperative school board reapportionment.", "T10", "adjacent"),
    "2022:HB1387": ("Would have let municipalities adopt a property tax homestead exemption.", "T1", "core"),
    "2022:HB1393": ("Would have enabled school district budget caps.", "T11", "core"),
    "2022:HB1399": ("Would have changed school district withdrawal from a cooperative school district.", "T10", "adjacent"),
    "2022:HB1412": ("Gardening and homesteading bill; matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2022:HB1417": ("Would have restored a state share of local employers' retirement system contributions.", "T8", "core"),
    "2022:HB1430": ("Would have repealed the motor vehicle rental tax under the meals and rooms tax.", "T6", "adjacent"),
    "2022:HB1478": ("Would have raised the business profits tax on certain large, low-wage employers.", "T4", "core"),
    "2022:HB1494": ("Would have changed the property tax exemption for certain communications services leases.", "T1", "adjacent"),
    "2022:HB1499": ("Would have made chartered public schools eligible for state school building aid.", "T3", "adjacent"),
    "2022:HB1500": ("Would have cut the communications services tax rate and repealed the tax in 2025.", "T6", "core"),
    "2022:HB1541": ("Would have created a business tax deferral for qualified startups.", "T4", "adjacent"),
    "2022:HB1552": ("Created a board for the certification of assessing persons (became law).", "T2", "core"),
    "2022:HB1565": ("Opioid abatement trust fund changes; matched by 'abatement' but not tax policy.", "CTX", "context"),
    "2022:HB1571": ("Littering fines for fish and game; matched by 'revenue' but not tax policy.", "CTX", "context"),
    "2022:HB1646": ("Would have changed representation on cooperative school district boards.", "T10", "adjacent"),
    "2022:HB1667": ("Updated the standard, optional, and all-veterans' property tax credits (became law).", "T1", "core"),
    "2022:HB1671": ("Changed the content of an adequate education (became law).", "T3", "adjacent"),
    "2022:HB1679": ("Would have addressed the dissolution and repeal of cooperative school districts.", "T10", "core"),
    "2022:HB210": ("Would have raised interest-and-dividends exemptions while trimming business R&D credits.", "T5", "core"),
    "2022:HB214": ("Would have required a public school facility condition assessment and changed school building aid grants.", "T3", "core"),
    "2022:HB252": ("Would have studied business tax credits for employers providing child care stipends.", "T4", "adjacent"),
    "2022:HB314": ("Homestead food operation licensure (became law); matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2022:HB353": ("Would have credited interest-and-dividends taxpayers for income tax paid to other states.", "T5", "core"),
    "2022:HB355": ("Adjusted keno rules (became law).", "T6", "adjacent"),
    "2022:HB400": ("Would have addressed collection of other states' sales taxes by New Hampshire businesses.", "T7", "adjacent"),
    "2022:HB410": ("Created a commission to study the assessing of power generation and utility transmission property (became law).", "T9", "core"),
    "2022:HB504": ("Would have changed the statewide education property tax and the low and moderate income homeowners relief program.", "T3", "core"),
    "2022:HB568": ("Would have raised interest-and-dividends exemptions and repealed the tax in 2025.", "T5", "core"),
    "2022:HB594": ("Would have changed the school building aid program.", "T3", "core"),
    "2022:HB608": ("Would have changed the formula for determining adequate education funding.", "T3", "core"),
    "2022:HB613": ("Would have changed special education state aid and pooled-risk cost recovery.", "T3", "adjacent"),
    "2022:HB623": ("Would have changed education funding.", "T3", "core"),
    "2022:HR17": ("House resolution opposing federal and state carbon taxes on fuels (adopted 178-159).", "T7", "adjacent"),
    "2022:SB135": ("Would have changed the calculation of the cost of an adequate education.", "T3", "core"),
    "2022:SB145": ("Would have made a temporary change to the school funding formula.", "T3", "core"),
    "2022:SB250": ("Would have let municipalities adopt a tax credit for qualified private community property owners.", "T1", "adjacent"),
    "2022:SB251": ("Changed the advisory board rules for tax increment financing districts (became law).", "T8", "adjacent"),
    "2022:SB252": ("Would have required more information on property tax bills.", "T2", "core"),
    "2022:SB275": ("Opioid abatement trust fund and commission (became law); matched by 'abatement' but not tax policy.", "CTX", "context"),
    "2022:SB312": ("Adjusted assessments of taxable property (became law).", "T2", "core"),
    "2022:SB315": ("Would have directed part of towns' meals-and-rooms distributions to reducing the local property tax rate.", "T8", "core"),
    "2022:SB317": ("Reduced the interest rate the state pays on abatements of paid property taxes (became law).", "T2", "core"),
    "2022:SB329": ("Housing-development barriers commission plus a local tax cap override procedure; the tax-cap piece is the tie to this issue.", "T11", "adjacent"),
    "2022:SB333": ("Case-management licensure bill carrying a state-share-of-retirement-contributions rider; died between the chambers.", "T8", "adjacent"),
    "2022:SB338": ("Would have let municipalities adopt a municipal occupancy fee.", "T8", "core"),
    "2022:SB343": ("Would have studied room occupancy tax revenues and the municipal distribution formula.", "T8", "core"),
    "2022:SB386": ("Set determination rules for adequate education grants and charter school tuition amounts (became law).", "T3", "adjacent"),
    "2022:SB420": ("Created the extraordinary need grant and raised special-education adequacy amounts (became law).", "T3", "core"),
    "2022:SB426": ("Would have changed fiscal 2023 adequate education grants.", "T3", "core"),
    "2022:SB435": ("Changed the net operating loss carryover under the business profits tax (became law).", "T4", "adjacent"),
    "2022:SB53": ("Department of Revenue Administration records confidentiality (became law); introduced as a community-preservation real-property surcharge and amended.", "T2", "adjacent"),
    # ---------------- 2023 ----------------
    "2023:CACR7": ("Constitutional amendment to let tax money fund religious educational institutions; failed the three-fifths threshold 192-191.", "T3", "adjacent"),
    "2023:HB100": ("Same bill as 2024 HB100 (interest and dividends tax repeal; carried across the biennium); see the 2024 record.", "T5", "core"),
    "2023:HB119": ("Homestead food licensure (became law); matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2023:HB121": ("Same bill as 2024 HB121 (worldwide combined reporting; carried across the biennium); see the 2024 record.", "T4", "core"),
    "2023:HB133": ("Same bill as 2024 HB133 (communications services tax repeal; carried across the biennium); see the 2024 record.", "T6", "core"),
    "2023:HB145": ("Same bill as 2024 HB145 (foreign sales tax collection; carried across the biennium); see the 2024 record.", "T7", "adjacent"),
    "2023:HB15": ("Same bill as 2024 HB15 (business enterprise tax rate; carried across the biennium); see the 2024 record.", "T4", "core"),
    "2023:HB174": ("Changed the filing of the notice of intent to cut timber - the timber tax's paperwork (became law).", "T9", "adjacent"),
    "2023:HB177": ("Would have changed which structures qualify for community revitalization (79-E) tax relief.", "T1", "adjacent"),
    "2023:HB192": ("Same bill as 2024 HB192 (I&D rate and exemptions; carried across the biennium); see the 2024 record.", "T5", "core"),
    "2023:HB197": ("Prorated property tax exemptions during the year (became law).", "T1", "adjacent"),
    "2023:HB2": ("The 2023 omnibus budget trailer itself; its tax and revenue sections are analyzed section-by-section in the HB2 analysis and excluded from bill counts to avoid double-counting.", "CTX", "context"),
    "2023:HB202": ("Same bill as 2024 HB202 (property tax abatements; carried across the biennium); see the 2024 record.", "T2", "core"),
    "2023:HB237": ("Set the asset-evaluation date for property tax exemption eligibility (became law).", "T1", "adjacent"),
    "2023:HB248": ("Directed revenue from commemorative liquor bottles (became law).", "T6", "adjacent"),
    "2023:HB265": ("Would have created municipal property tax relief for fire suppression system installation.", "T1", "adjacent"),
    "2023:HB285": ("Put the state equalization manual into administrative rules (became law).", "T2", "core"),
    "2023:HB288": ("Would have changed the taxation of sole proprietorship businesses.", "T4", "adjacent"),
    "2023:HB294": ("Would have let municipalities adopt a local child tax credit.", "T1", "adjacent"),
    "2023:HB332": ("Same bill as 2024 HB332 (school building aid projects; carried across the biennium); see the 2024 record.", "T3", "core"),
    "2023:HB334": ("Would have changed the determination and cost of a state adequate education.", "T3", "core"),
    "2023:HB335": ("Required notice of tax liens on real estate subject to old-age-assistance liens (became law).", "T2", "adjacent"),
    "2023:HB354": ("Same bill as 2024 HB354 (charter school building aid; carried across the biennium); see the 2024 record.", "T3", "adjacent"),
    "2023:HB365": ("Ordered a statewide facility condition assessment of school buildings (became law).", "T3", "adjacent"),
    "2023:HB377": ("Dyslexia screening in schools with an adequacy grant add-on for screened pupils (became law).", "T3", "adjacent"),
    "2023:HB394": ("Would have changed the organization of cooperative school boards.", "T10", "adjacent"),
    "2023:HB403": ("Would have changed selectmen's and assessors' authority to abate taxes.", "T2", "core"),
    "2023:HB412": ("Road-toll alternatives commission (became law); highway-fund transportation revenue, kept for audit.", "CTX", "context"),
    "2023:HB433": ("Same bill as 2024 HB433 (exemptions ending at home sale; carried across the biennium); see the 2024 record.", "T1", "adjacent"),
    "2023:HB435": ("Would have changed relief-aid calculations in adequate education grants.", "T3", "core"),
    "2023:HB440": ("Would have changed the permitted uses of the education trust fund.", "T3", "core"),
    "2023:HB450": ("Same bill as 2024 HB450 (business profits tax net-operating-loss limit; carried across the biennium); see the 2024 record.", "T4", "adjacent"),
    "2023:HB452": ("Streamlined the department of education's school building aid application procedures (became law).", "T3", "adjacent"),
    "2023:HB510": ("Would have removed the premium-cigar exemption from the tobacco tax.", "T6", "adjacent"),
    "2023:HB530": ("Changed the procedure for withdrawing from a cooperative school district (became law).", "T10", "core"),
    "2023:HB531": ("Would have changed the taxation of tobacco and nicotine products.", "T6", "adjacent"),
    "2023:HB540": ("Same bill as 2024 HB540 (special education adequacy amounts; carried across the biennium); see the 2024 record.", "T3", "adjacent"),
    "2023:HB541": ("Same bill as 2024 HB541 (school building aid grants and appropriation; carried across the biennium); see the 2024 record.", "T3", "core"),
    "2023:HB546": ("Same bill as 2024 HB546 (school building aid program; carried across the biennium); see the 2024 record.", "T3", "core"),
    "2023:HB568": ("Would have assessed all state adequacy and local education costs through the state education warrant.", "T3", "core"),
    "2023:HB569": ("Same bill as 2024 HB569 (SWEPT and homeowner relief; carried across the biennium); see the 2024 record.", "T3", "core"),
    "2023:HB576": ("Set administration rules for commercial property assessed clean energy (C-PACE) districts (became law).", "T8", "adjacent"),
    "2023:HB577": ("Same bill as 2024 HB577 (special education state aid; carried across the biennium); see the 2024 record.", "T3", "adjacent"),
    "2023:HB632": ("Would have changed the cooperative school district budget committee.", "T10", "adjacent"),
    "2023:HB649": ("Would have repealed collection of the statewide education property tax.", "T3", "core"),
    "2023:HB71": ("Repealed a department of education report on charter school funding (became law); administrative housekeeping.", "CTX", "context"),
    "2023:HB80": ("Would have granted tax-exempt status to county real property leased for agriculture.", "T1", "adjacent"),
    "2023:HB98": ("Would have changed applications for the low and moderate income homeowners property tax relief program.", "T1", "core"),
    "2023:HB99": ("Would have required property tax bills to carry information about the state's rebate program for lower-income homeowners.", "T1", "core"),
    "2023:HR16": ("House resolution about the Internal Revenue Service; federal tax administration, not New Hampshire policy.", "CTX", "context"),
    "2023:HR17": ("House resolution affirming revenue estimates for fiscal 2023-2025.", "T8", "adjacent"),
    "2023:SB104": ("Would have regulated online gambling and directed proceeds to community college scholarships.", "T6", "adjacent"),
    "2023:SB114": ("Would have restored a state share of local employers' retirement system contributions.", "T8", "core"),
    "2023:SB189": ("Adjusted the definition of gross business profits in computing taxable business profits (became law).", "T4", "adjacent"),
    "2023:SB20": ("Adjusted keno license applications and fees (became law).", "T6", "adjacent"),
    "2023:SB222": ("Made broadband infrastructure a revenue-producing facility eligible for municipal revenue bonds (became law).", "T8", "adjacent"),
    "2023:SB225": ("Created the commission to study the assessing of power generation property (became law).", "T9", "core"),
    "2023:SB231": ("Historic housing tax credit plus workforce/affordable housing appropriations; the credit is the tie to this issue.", "T4", "adjacent"),
    "2023:SB260": ("Would have changed business profits tax deductions for member and owner compensation.", "T4", "adjacent"),
    "2023:SB261": ("Would have changed the interest and dividends tax rate and threshold.", "T5", "core"),
    "2023:SB262": ("Would have let municipalities collect an occupancy fee from local room-rental operators.", "T8", "core"),
    "2023:SB266": ("Statewide education improvement and assessment program (became law); education testing, not funding.", "CTX", "context"),
    "2023:SB32": ("Opioid abatement trust fund changes (became law); matched by 'abatement' but not tax policy.", "CTX", "context"),
    "2023:SB63": ("Would have let municipalities adopt a tax credit for qualified private community property owners; vetoed.", "T1", "adjacent"),
    "2023:SB90": ("Would have created a commission to study charitable gambling.", "T6", "adjacent"),
    # ---------------- 2024 ----------------
    "2024:CACR15": ("Constitutional amendment requiring a two-thirds vote for new or increased taxes and fees.", "T7", "core"),
    "2024:CACR18": ("Constitutional amendment providing that churches shall not be exempt from state taxes.", "T1", "core"),
    "2024:HB100": ("Would have repealed the interest and dividends tax ahead of schedule; sent to interim study.", "T5", "core"),
    "2024:HB1001": ("Would have exempted Masonic lodges from property taxation.", "T1", "adjacent"),
    "2024:HB1018": ("Liquor licensing bill that also changed current use land rules (became law).", "T9", "adjacent"),
    "2024:HB1034": ("Would have let municipalities adopt a homestead property tax exemption; sent to interim study.", "T1", "core"),
    "2024:HB1040": ("Would have added DRA-rate interest to abated property tax refunds.", "T2", "adjacent"),
    "2024:HB1055": ("Rewrote the property tax exemption for charitable organizations (became law).", "T1", "core"),
    "2024:HB1105": ("Clarified how a local tax cap applies (became law).", "T11", "core"),
    "2024:HB1106": ("Would have changed net asset limits under the elderly property tax exemption.", "T1", "core"),
    "2024:HB1128": ("Would have redefined scholarship organizations for the education tax credit.", "T4", "adjacent"),
    "2024:HB1154": ("Extended property tax exemptions for certain disabled veterans (became law).", "T1", "core"),
    "2024:HB1180": ("Homestead right (creditor protection) for non-titled spouses; matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2024:HB1191": ("Exempted restaurant-voucher program participants from the meals and rooms tax (became law).", "T6", "adjacent"),
    "2024:HB1193": ("Would have created a child care business tax credit program.", "T4", "adjacent"),
    "2024:HB121": ("Would have required worldwide combined reporting for unitary businesses under the business profits tax.", "T4", "core"),
    "2024:HB1219": ("Would have studied a legislative office for cost-benefit analysis of budget and revenue bills.", "T8", "adjacent"),
    "2024:HB1223": ("Would have created local options for games of chance; died between the chambers.", "T6", "adjacent"),
    "2024:HB1254": ("Would have created an optional local public-safety assessment on room occupancies.", "T8", "core"),
    "2024:HB1258": ("Would have created a property tax waiver for disabled veterans.", "T1", "core"),
    "2024:HB1265": ("Set penalties for missing school expenditure reports and required expense reporting tied to adequacy grants (became law).", "T3", "adjacent"),
    "2024:HB1279": ("Would have restored a state share of local employers' retirement system contributions; sent to interim study.", "T8", "core"),
    "2024:HB1317": ("Would have changed municipal filings for tax-exempt charitable organizations.", "T1", "adjacent"),
    "2024:HB1318": ("Opioid abatement advisory commission duties (became law); matched by 'abatement' but not tax policy.", "CTX", "context"),
    "2024:HB133": ("Would have repealed the communications services tax; sent to interim study.", "T6", "core"),
    "2024:HB1383": ("Would have changed cooperative school board district elections; interim study.", "T10", "adjacent"),
    "2024:HB1389": ("Lottery winner anonymity; gaming administration, not revenue policy.", "CTX", "context"),
    "2024:HB1422": ("Would have changed the rates of the business profits, business enterprise, communications services, and meals and rooms taxes; interim study.", "T4", "core"),
    "2024:HB1449": ("Would have limited board of tax and land appeals reappraisal orders.", "T2", "adjacent"),
    "2024:HB145": ("Would have addressed collection of other states' sales taxes by New Hampshire businesses.", "T7", "adjacent"),
    "2024:HB1456": ("Changed appointment and removal of board of tax and land appeals and housing appeals board members (became law).", "T2", "adjacent"),
    "2024:HB1464": ("Road-toll alternatives study; highway-fund transportation revenue, kept for audit.", "CTX", "context"),
    "2024:HB1470": ("Would have studied a state low-income housing tax credit.", "T4", "adjacent"),
    "2024:HB1481": ("Cooperative school board vacancy appointments; governance housekeeping.", "CTX", "context"),
    "2024:HB1484": ("Would have changed current use taxation for certain forested lands.", "T9", "core"),
    "2024:HB1492": ("Would have changed the interest and dividends tax rate and exemptions; interim study.", "T5", "core"),
    "2024:HB1493": ("Would have changed the powers of cooperative school district budget committees; interim study.", "T10", "adjacent"),
    "2024:HB15": ("Would have changed the business enterprise tax rate; sent to interim study.", "T4", "core"),
    "2024:HB1515": ("Would have changed the meals and rooms tax rate.", "T6", "core"),
    "2024:HB1517": ("Would have tied the statewide education property tax to excess games-of-chance revenue.", "T3", "core"),
    "2024:HB1525": ("Adjusted credits under the business profits and business enterprise taxes (became law).", "T4", "adjacent"),
    "2024:HB1531": ("Would have allowed the federal bonus-depreciation deduction under the business profits tax.", "T4", "adjacent"),
    "2024:HB1533": ("Would have changed the safe-harbor compensation amount under the business profits tax; interim study.", "T4", "adjacent"),
    "2024:HB1536": ("Would have raised the business profits tax expense deduction; interim study.", "T4", "adjacent"),
    "2024:HB1551": ("Would have distinguished C corporations from S corporations under the business profits tax.", "T4", "adjacent"),
    "2024:HB1555": ("Would have allowed special meetings for education funding changes; interim study.", "T3", "adjacent"),
    "2024:HB1560": ("Would have directed unassigned education trust fund money.", "T3", "core"),
    "2024:HB1563": ("Would have addressed the education property tax and political subdivisions' authority; interim study.", "T3", "core"),
    "2024:HB1570": ("Would have required a facility assessment of public and chartered public schools; interim study.", "T3", "adjacent"),
    "2024:HB1583": ("Would have changed the per-pupil cost of an adequate education; interim study.", "T3", "core"),
    "2024:HB1631": ("Road-toll alternatives commission (became law); highway-fund transportation revenue, kept for audit.", "CTX", "context"),
    "2024:HB1642": ("Would have defined cooperative board members' budget-committee role; interim study.", "T10", "adjacent"),
    "2024:HB1651": ("Would have combined the board of tax and land appeals and the housing appeals board.", "T2", "adjacent"),
    "2024:HB1656": ("Would have changed special-education adequacy grant amounts; interim study.", "T3", "adjacent"),
    "2024:HB1675": ("Would have adjusted adequacy grants based on pupil proficiency.", "T3", "adjacent"),
    "2024:HB1685": ("Homestead-to-artisan foods rewrite; matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2024:HB1686": ("Would have required excess statewide education property tax to be remitted to the education trust fund and barred negative local rates.", "T3", "core"),
    "2024:HB192": ("Would have changed the interest and dividends tax rate and exemptions.", "T5", "core"),
    "2024:HB202": ("Changed property tax abatement rules (became law).", "T2", "core"),
    "2024:HB332": ("Would have changed school building aid for eligible projects.", "T3", "core"),
    "2024:HB354": ("Made chartered public schools eligible for state school building aid (became law).", "T3", "adjacent"),
    "2024:HB433": ("Would have ended property tax exemptions at a home's sale rather than transferring them.", "T1", "adjacent"),
    "2024:HB450": ("Would have removed the net operating loss deduction limit under the business profits tax; interim study.", "T4", "adjacent"),
    "2024:HB458": ("Re-established the commission to study the assessing of power generation property (became law).", "T9", "core"),
    "2024:HB540": ("Would have changed special-education adequacy grant amounts.", "T3", "adjacent"),
    "2024:HB541": ("Would have funded school building aid grants with an appropriation.", "T3", "core"),
    "2024:HB546": ("Would have changed the school building aid program; interim study.", "T3", "core"),
    "2024:HB569": ("Would have changed the statewide education property tax and the low and moderate income homeowners relief program; interim study.", "T3", "core"),
    "2024:HB577": ("Would have changed state aid for special education pupils; died on the table.", "T3", "adjacent"),
    "2024:HCR10": ("House resolution urging Congress to fund special education to reduce New Hampshire property taxes (adopted by voice vote).", "T3", "adjacent"),
    "2024:SB305": ("Would have let cigarette wholesalers retain part of the tax collected per stamped package.", "T6", "adjacent"),
    "2024:SB311": ("Property tax offset and appropriation for the town of Hampstead (became law).", "T8", "adjacent"),
    "2024:SB324": ("Lottery license renewal notices (became law); gaming administration.", "CTX", "context"),
    "2024:SB326": ("Lottery infraction adjudication; gaming administration.", "CTX", "context"),
    "2024:SB342": ("Would have funded school building aid; died at the Senate's deadline.", "T3", "core"),
    "2024:SB364": ("Would have created a historic housing preservation tax credit; interim study.", "T4", "adjacent"),
    "2024:SB383": ("Clarified local tax cap provisions (became law).", "T11", "core"),
    "2024:SB433": ("Created a study committee on e-cigarette marketing and tax collection (became law).", "T6", "adjacent"),
    "2024:SB434": ("Would have exempted extended-stay housing program businesses from the meals and rooms tax.", "T6", "adjacent"),
    "2024:SB454": ("Would have doubled the real estate transfer tax revenue flowing to the affordable housing fund.", "T6", "adjacent"),
    "2024:SB472": ("Historic horse racing licensing with games-of-chance revenue for host communities (became law).", "T6", "adjacent"),
    "2024:SB504": ("Would have changed current use land rules; died between the chambers.", "T9", "core"),
    "2024:SB514": ("Adjusted the timber tax (became law).", "T9", "adjacent"),
    "2024:SB526": ("Would have required school facility condition assessments and temperature-control building aid.", "T3", "adjacent"),
    "2024:SB532": ("Would have required municipalities and school boards to post state funds received; died between the chambers.", "T8", "adjacent"),
    "2024:SB552": ("Would have addressed lapses from the education trust fund; interim study.", "T3", "core"),
    "2024:SB584": ("Would have addressed the utility property tax on renewables and communications services tax revenue; interim study.", "T9", "core"),
    "2024:SB585": ("Created a property lien for unpaid meals and rooms taxes (became law).", "T6", "adjacent"),
    "2024:SB586": ("Would have granted tax-exempt status to the Odd Fellows; interim study.", "T1", "adjacent"),
    # ---------------- 2025 ----------------
    "2025:HB101": ("Would have exempted certain elderly homeowners from property taxes.", "T1", "core"),
    "2025:HB123": ("Defined pre-sequestration timber tax revenue and paused carbon-sequestration deals (became law).", "T9", "adjacent"),
    "2025:HB135": ("Would have addressed collection of other states' sales taxes by New Hampshire businesses.", "T7", "adjacent"),
    "2025:HB137": ("Would have let municipalities keep excess statewide education property tax money for local school and municipal purposes.", "T3", "core"),
    "2025:HB147": ("Would have clarified the property tax exemptions for religious, educational, and charitable organizations.", "T1", "core"),
    "2025:HB150": ("Homestead food operations and commercial kitchens (became law); matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2025:HB2": ("The 2025 omnibus budget trailer itself; its tax and revenue sections are analyzed section-by-section in the HB2 analysis and excluded from bill counts to avoid double-counting.", "CTX", "context"),
    "2025:HB200": ("Changed the procedure for overriding a local tax cap (became law).", "T11", "core"),
    "2025:HB237": ("Would have restricted special-education aid to students receiving special education services.", "T3", "adjacent"),
    "2025:HB255": ("Would have raised the share of business profits tax revenue deposited in the education trust fund.", "T4", "core"),
    "2025:HB279": ("Homestead food recipe study (became law); matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2025:HB282": ("First-responder benefits bill that also adjusted education adequacy grant determination (became law).", "T3", "adjacent"),
    "2025:HB283": ("Would have changed the list of subjects in an adequate education.", "T3", "adjacent"),
    "2025:HB304": ("Homestead kitchen labeling (became law); matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2025:HB307": ("Homestead food production areas (became law); matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2025:HB318": ("Would have raised the share of business enterprise tax revenue deposited in the education trust fund.", "T4", "core"),
    "2025:HB374": ("Rewrote local tax cap and budget laws (became law).", "T11", "core"),
    "2025:HB394": ("Defined cooperative school district budget committee powers and board members' roles (became law).", "T10", "adjacent"),
    "2025:HB412": ("Cooperative school board vacancy elections; governance housekeeping.", "CTX", "context"),
    "2025:HB426": ("Let charitable organizations claim property tax exemptions for the prior tax year (became law).", "T1", "adjacent"),
    "2025:HB447": ("Would have changed property tax exemptions for disabled veterans.", "T1", "core"),
    "2025:HB483": ("Would have redefined scholarship organizations for the education tax credit.", "T4", "adjacent"),
    "2025:HB485": ("Lottery winner anonymity (became law); gaming administration.", "CTX", "context"),
    "2025:HB502": ("Would have required complete corporate reporting for unitary businesses and changed statewide education property tax revenue handling.", "T4", "core"),
    "2025:HB503": ("Would have changed how tax revenues are allocated to the education trust fund.", "T3", "core"),
    "2025:HB505": ("Homestead freeze-dried foods (became law); matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2025:HB506": ("Firearms and driver's license omnibus (became law); matched by search terms but not a tax bill.", "CTX", "context"),
    "2025:HB515": ("Would have repealed chartered public schools' eligibility for school building aid.", "T3", "adjacent"),
    "2025:HB527": ("Would have replaced the statewide education property tax with a local revenue contribution.", "T3", "core"),
    "2025:HB530": ("Would have raised the real estate transfer tax share flowing to the affordable housing fund.", "T6", "adjacent"),
    "2025:HB531": ("Would have capped charitable gaming revenue distributed to any one charity.", "T6", "adjacent"),
    "2025:HB550": ("Would have modified the base cost of an adequate education.", "T3", "core"),
    "2025:HB560": ("Medical records and DUI omnibus; matched by search terms but not a tax bill.", "CTX", "context"),
    "2025:HB588": ("Would have changed the distribution of historic horse racing pari-mutuel revenue.", "T6", "adjacent"),
    "2025:HB591": ("Extended keno gaming hours (became law).", "T6", "adjacent"),
    "2025:HB596": ("Would have set reporting requirements for meals and rooms tax collectors.", "T6", "adjacent"),
    "2025:HB603": ("Would have raised the adequacy grant for special education pupils.", "T3", "adjacent"),
    "2025:HB617": ("Homestead right (creditor protection) rewrite (became law); matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2025:HB642": ("Homestead dehydrated meat sales; matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2025:HB649": ("Vehicle inspection repeal (became law); matched by 'abatement' (air pollution fund) but not a tax bill.", "CTX", "context"),
    "2025:HB669": ("Would have sent all statewide education property tax revenue to the education trust fund with one equalized statewide rate.", "T3", "core"),
    "2025:HB675": ("Would have raised the statewide education property tax and required towns to remit the excess to the state.", "T3", "core"),
    "2025:HB689": ("Would have let municipalities adopt a volunteer-incentive property tax credit.", "T1", "core"),
    "2025:HB696": ("Set how utility property taxes and statewide education property taxes apply to electric generating facilities (became law).", "T9", "core"),
    "2025:HB737": ("Created local options for games of chance, statewide keno, and new charitable gaming fees (became law).", "T6", "adjacent"),
    "2025:HB746": ("Would have awarded attorney's fees for successful local assessment appeals.", "T2", "adjacent"),
    "2025:HB766": ("Would have let municipalities exempt certain elderly residents from the local education property tax.", "T1", "core"),
    "2025:HB769": ("Would have changed the base adequacy cost per pupil and the statewide education property tax rate.", "T3", "core"),
    "2025:HB782": ("Would have expanded elderly and disabled property tax exemptions and required public awareness of relief programs.", "T1", "core"),
    "2025:HB99": ("Created a property tax waiver for disabled veterans (became law).", "T1", "core"),
    "2025:HR17": ("House resolution affirming revenue estimates for fiscal 2025-2027.", "T8", "adjacent"),
    "2025:SB168": ("Would have legalized online gambling with proceeds to the education trust fund, general fund, and municipal exemption reimbursements; died at the Senate's deadline.", "T6", "adjacent"),
    "2025:SB173": ("Adjusted assessment of residential property under low income housing tax credit covenants (became law).", "T2", "adjacent"),
    "2025:SB20": ("Would have restored a state share of local employers' retirement system contributions; died at the Senate's deadline.", "T8", "core"),
    "2025:SB209": ("School building aid project-manager requirements with a lawsuit-financing rider; died between the chambers.", "T3", "adjacent"),
    "2025:SB217": ("Would have required public notice of historic tax rates and the tax impact of proposed projects.", "T2", "core"),
    "2025:SB224": ("Would have raised the maximum optional veterans' tax credit.", "T1", "core"),
    "2025:SB275": ("Would have provided property tax relief for some child care agencies.", "T1", "adjacent"),
    "2025:SB276": ("Would have raised the research and development tax credit; died at the Senate's deadline.", "T4", "adjacent"),
    "2025:SB277": ("Would have set utility property tax and SWEPT treatment of electric generating facilities; died at the deadline (enacted via HB696).", "T9", "core"),
    "2025:SB291": ("Clarified the religious-use property tax exemption (became law).", "T1", "core"),
    "2025:SB46": ("Would have conditioned current use eligibility near new construction on vegetated buffers.", "T9", "adjacent"),
    "2025:SB55": ("Would have exempted qualifying housing projects from the land use change tax.", "T9", "adjacent"),
    "2025:SB81": ("Would have raised the transfer-tax contribution to the affordable housing fund; died at the Senate's deadline.", "T6", "adjacent"),
    "2025:SB83": ("Created a state fund reimbursing towns for elderly, disabled, blind, and deaf property tax exemptions - funded by newly authorized video lottery terminals (became law).", "T1", "core"),
    # ---------------- 2026 ----------------
    "2026:CACR18": ("Constitutional amendment capping how fast state tax rates may rise each year.", "T7", "core"),
    "2026:HB1002": ("Would have repealed the solar energy systems property tax exemption.", "T1", "adjacent"),
    "2026:HB1021": ("Moved the notice date for electing low income housing tax credit assessment (became law).", "T2", "adjacent"),
    "2026:HB1063": ("Would have reduced the share of meals and rooms taxes operators keep for collecting.", "T6", "adjacent"),
    "2026:HB1068": ("Would have taxed long-term permanent-residence occupants under the meals and rooms tax; interim study.", "T6", "adjacent"),
    "2026:HB1090": ("Would have changed the meals and rooms tax.", "T6", "adjacent"),
    "2026:HB1102": ("Would have raised the research and development tax credit cap (with a state park fee rider); vetoed.", "T4", "adjacent"),
    "2026:HB1103": ("Widened the property types eligible for community revitalization (79-E) tax relief (became law).", "T1", "adjacent"),
    "2026:HB1104": ("Would have changed the priority order for school building aid grants.", "T3", "adjacent"),
    "2026:HB1121": ("Would have defined the cost of an adequate education.", "T3", "core"),
    "2026:HB1144": ("Would have amended the excavation tax rate.", "T9", "adjacent"),
    "2026:HB1194": ("Insurance premium assessment credits with a gambling-statute rider (became law).", "T6", "adjacent"),
    "2026:HB1210": ("Child tax credit allocation in child support cases; family law, not tax policy.", "CTX", "context"),
    "2026:HB1227": ("Would have changed how the local tax cap is calculated.", "T11", "core"),
    "2026:HB1230": ("Would have restricted increases in state tax rates and debts.", "T7", "core"),
    "2026:HB1278": ("Would have given municipalities a grace period to adopt simple-majority tax cap overrides.", "T11", "core"),
    "2026:HB1296": ("Would have changed the conditions and adoption procedures for the elderly property tax exemption.", "T1", "core"),
    "2026:HB1300": ("Put school district tax cap questions on the 2026 and 2028 general election ballots, with administrative expense limits (became law).", "T11", "core"),
    "2026:HB1324": ("Would have exempted Masonic lodges from property taxation.", "T1", "adjacent"),
    "2026:HB1331": ("Let the Derry town council absorb the Derry Cooperative School District as a town department by charter amendment (became law).", "T10", "core"),
    "2026:HB1374": ("Rewrote the procedures for withdrawing from a cooperative school district and closing schools (became law).", "T10", "core"),
    "2026:HB1383": ("Would have changed the methods for overriding local tax caps.", "T11", "core"),
    "2026:HB1385": ("Would have barred negative property tax rates in certain municipalities - the statewide education property tax donor-town mechanics.", "T3", "core"),
    "2026:HB1399": ("Would have paid Claremont school renovation costs from the rainy day fund.", "T3", "adjacent"),
    "2026:HB1400": ("Would have created an opt-out mechanism for property tax exemptions and credits.", "T1", "adjacent"),
    "2026:HB1409": ("Would have changed where video lottery terminal revenue is deposited.", "T6", "adjacent"),
    "2026:HB1420": ("Would have created a temporary local newspaper advertisement tax credit; interim study.", "T4", "adjacent"),
    "2026:HB1433": ("Created a child care tax credit for qualifying businesses (became law).", "T4", "adjacent"),
    "2026:HB1434": ("Would have let municipalities vote on allowing keno sales.", "T6", "adjacent"),
    "2026:HB1474": ("Would have changed the formula distributing meals and rooms tax revenue to municipalities.", "T8", "core"),
    "2026:HB1480": ("Would have raised the meals and rooms tax rate.", "T6", "core"),
    "2026:HB1494": ("Raised the maximum optional veterans', combat service, and surviving spouse tax credits (became law).", "T1", "core"),
    "2026:HB1505": ("Would have required municipalities to document tax-cap compliance to the state; interim study.", "T11", "adjacent"),
    "2026:HB1514": ("Required school monitoring and financial reports to go to school authorities (became law).", "T3", "adjacent"),
    "2026:HB1516": ("Would have let towns vote to require charts and QR codes on property tax bills showing where tax dollars go; interim study.", "T2", "core"),
    "2026:HB1528": ("Would have changed the methods for rescinding local tax caps.", "T11", "core"),
    "2026:HB1546": ("Would have repealed the business profits tax.", "T4", "core"),
    "2026:HB155": ("Adjusted business enterprise tax returns, with a nursing-facility appropriation (became law).", "T4", "adjacent"),
    "2026:HB1559": ("Would have raised the share of gaming revenue going to problem-gambling services.", "T6", "adjacent"),
    "2026:HB1565": ("Child-protection bill carrying a school building aid project-manager rider; vetoed.", "T3", "adjacent"),
    "2026:HB1579": ("Would have created a committee to study ways of raising revenue for additional education spending; interim study.", "T3", "core"),
    "2026:HB1580": ("Would have changed the taxation of non-primary residences.", "T1", "core"),
    "2026:HB1597": ("Would have changed business profits tax expense deductions.", "T4", "adjacent"),
    "2026:HB1629": ("Would have repealed the business enterprise tax.", "T4", "core"),
    "2026:HB1636": ("Would have directed the Department of Revenue Administration to study options for generating state revenue.", "T7", "core"),
    "2026:HB1644": ("Would have permitted towns to unilaterally withdraw from cooperative school districts; interim study.", "T10", "core"),
    "2026:HB1646": ("Would have created an off-site infrastructure improvement business tax credit; interim study.", "T4", "adjacent"),
    "2026:HB1647": ("Would have changed the taxation of farms and farm structures; interim study.", "T9", "adjacent"),
    "2026:HB1648": ("Would have created property tax exemptions for qualifying residences; interim study.", "T1", "core"),
    "2026:HB1659": ("Would have expanded local property tax exemptions for 100-percent disabled veterans.", "T1", "core"),
    "2026:HB1668": ("Would have changed how the Internal Revenue Code applies to the business profits tax.", "T4", "adjacent"),
    "2026:HB1674": ("Would have created a property tax exemption for certain lower-income property owners.", "T1", "core"),
    "2026:HB1677": ("Would have required budget-committee recommendations on tax-impact warrant articles under a local cap.", "T11", "adjacent"),
    "2026:HB1691": ("Would have changed the limitations and qualifications for land in current use.", "T9", "core"),
    "2026:HB1707": ("Would have taxed certain unoccupied properties and exempted low- and moderate-income buyers from the transfer tax.", "T7", "core"),
    "2026:HB1708": ("Would have changed statewide education property taxes and other tax revenues.", "T3", "core"),
    "2026:HB1724": ("Electric utility charge transparency; utility regulation, not tax policy.", "CTX", "context"),
    "2026:HB1756": ("Let organizations file once for property tax exemptions that continue until found ineligible (became law).", "T1", "adjacent"),
    "2026:HB1786": ("Would have assessed luxury second homes to fund statewide housing development programs.", "T7", "core"),
    "2026:HB1787": ("Would have modified the statewide education property tax; interim study.", "T3", "core"),
    "2026:HB1799": ("Would have required full state funding of an adequate education opportunity.", "T3", "core"),
    "2026:HB1800": ("Would have changed statewide education property taxes; interim study.", "T3", "core"),
    "2026:HB1803": ("Would have barred holding an education tax credit scholarship and an education freedom account in the same year.", "T4", "adjacent"),
    "2026:HB1807": ("Required tax rate and tax impact information on warrant articles (became law).", "T2", "core"),
    "2026:HB1812": ("Mental health access adequacy evaluation; matched by 'adequacy' but not a tax bill.", "CTX", "context"),
    "2026:HB1823": ("Would have required schools and districts to publish independent audits and financial reports.", "T3", "adjacent"),
    "2026:HB1826": ("Would have changed the cost of an opportunity for an adequate education.", "T3", "core"),
    "2026:HB1831": ("Would have repealed the education trust fund targeted aid cap.", "T3", "core"),
    "2026:HB197": ("Would have restored a state share of local employers' retirement system contributions.", "T8", "core"),
    "2026:HB295": ("Would have made school building aid funds nonlapsing.", "T3", "adjacent"),
    "2026:HB366": ("Would have changed the priority of school building aid applications.", "T3", "adjacent"),
    "2026:HB417": ("Would have repealed the communications services tax; interim study.", "T6", "core"),
    "2026:HB491": ("Would have studied alternative public education funding methods to reduce reliance on local property taxes.", "T3", "core"),
    "2026:HB563": ("Would have rewritten adequacy costs, extraordinary need grants, fiscal capacity disparity aid, and grant determination.", "T3", "core"),
    "2026:HB585": ("Would have changed the property tax exemption for religious organizations.", "T1", "core"),
    "2026:HB590": ("Cooperative school board election rules; governance housekeeping.", "CTX", "context"),
    "2026:HB609": ("Firearms authority omnibus; matched by 'taxation' in a list but not a tax bill.", "CTX", "context"),
    "2026:HB651": ("Would have modified the base cost and differential aid of an adequate education.", "T3", "core"),
    "2026:HB660": ("Would have required historic horse racing facilities to share machine revenue with host communities; interim study.", "T6", "adjacent"),
    "2026:HB728": ("Would have authorized video lottery terminals and repealed historic horse racing licensing.", "T6", "adjacent"),
    "2026:HB734": ("Would have changed the state education property tax and the low- and moderate-income homeowners relief program; interim study.", "T3", "core"),
    "2026:HB742": ("Would have drawn catastrophic special education aid from the education trust fund; interim study.", "T3", "adjacent"),
    "2026:HCR11": ("Would have declared the Claremont school-funding directives non-binding on the political branches.", "T3", "core"),
    "2026:SB220": ("Would have required public hearings and deliberation before denying tax exemptions.", "T2", "adjacent"),
    "2026:SB404": ("Would have changed economic revitalization zone tax credits.", "T4", "adjacent"),
    "2026:SB418": ("Homestead food licensing preemption (became law); matched by 'homestead' but not a tax bill.", "CTX", "context"),
    "2026:SB485": ("Would have regulated and taxed hemp-based products; interim study.", "T7", "adjacent"),
    "2026:SB491": ("Education freedom account career-and-technical spending (became law); EFA mechanics, not tax policy.", "CTX", "context"),
    "2026:SB513": ("Would have required an owner's project manager on school building aid projects; died between the chambers.", "T3", "adjacent"),
    "2026:SB514": ("Would have protected municipal tax-cap ballot questions from alteration; interim study.", "T11", "core"),
    "2026:SB582": ("Would have modified the base cost of an adequate education.", "T3", "core"),
    "2026:SB583": ("Would have created an education funding transparency data and reporting system.", "T3", "adjacent"),
    "2026:SB600": ("Required quarterly reports to the fiscal committee on the general and education trust funds (became law).", "T8", "adjacent"),
    "2026:SB635": ("Would have created a health reimbursement arrangement tax credit with DRA system money.", "T4", "adjacent"),
    "2026:SB636": ("Would have created small-business tax credits for documented tariff costs.", "T4", "adjacent"),
    "2026:SB637": ("Would have created tax credits for purchases from New Hampshire farms; interim study.", "T4", "adjacent"),
    "2026:SB643": ("Would have required municipal documentation of budget and tax cap compliance; died between the chambers.", "T11", "adjacent"),
    "2026:SB645": ("Child care scholarship funding reallocation; spending policy, not tax structure.", "CTX", "context"),
    "2026:SB652": ("Changed the maximum tax credit award for overpaid taxes (became law).", "T2", "adjacent"),
    "2026:SB654": ("Would have created business tax credits for on-site child care and employee health coverage.", "T4", "adjacent"),
}


def main() -> None:
    disp = {f"{b['session_year']}:{b['bill_no']}": b
            for b in json.loads((W / "dispositions.json").read_text())["bills"]}
    missing = [k for k in disp if k not in E]
    extra = [k for k in E if k not in disp]
    assert not missing, f"bills without curation ({len(missing)}): {missing[:20]}"
    assert not extra, f"curation for unknown bills: {extra[:20]}"

    bills = []
    for key, (topic, tkey, rel) in sorted(E.items()):
        d = disp[key]
        bills.append({
            "bill_key": key,
            "session_year": d["session_year"],
            "bill_no": d["bill_no"],
            "title": d["title"],
            "plain_topic": topic,
            "theme": THEMES[tkey],
            "relevance": rel,
            "disposition": d["disposition"],
            "stage": d["stage"],
            "roll_call_count": d["roll_call_count"],
        })
    from collections import Counter
    out = {
        "issue": "new-hampshire-02-property-taxes",
        "note": ("Curation of the keyword-discovered set: one plain sentence, one "
                 "theme, and a relevance tier per bill. 'context' bills are kept "
                 "for audit but excluded from headline numbers; first-year records "
                 "of biennium carryover bills are counted once, in their decision "
                 "year."),
        "themes": list(THEMES.values()),
        "counts": {
            "total": len(bills),
            "by_relevance": dict(Counter(b["relevance"] for b in bills)),
            "policy_set": sum(1 for b in bills if b["relevance"] != "context"
                              and b["disposition"] != "carryover_duplicate"),
        },
        "bills": bills,
    }
    (W / "curation-map.json").write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(json.dumps(out["counts"], indent=1))
    print(dict(Counter(b["theme"] for b in bills)))


if __name__ == "__main__":
    main()
